# Reuters 46-class classification: regularization experiments

Exploratory notebook (code unchanged from the original run; figures were removed from the saved outputs to keep the file small and are available in `results/`).

**Flow:** load data → multi-hot vectorization → baseline (64-64) → larger models that overfit (512-512, 128-128) → L2, L1, L1+L2, Dropout and Dropout+L2 experiments → grid comparison of 27 configurations (128-128, 30 epochs).

**Evaluation:** all numbers in this notebook are *validation* accuracies on a 1,000-sample hold-out set (`x_train[:1000]`); the test set is not used here (see notebook 02). The last cells re-run the same grid, so the numbers differ slightly between those cells because of random initialization.

In [1]:
from keras.datasets import reuters
import numpy as np

# بارگیری دیتاست با ۱۰٬۰۰۰ کلمه پرتکرار
(train_data, train_labels), (test_data, test_labels) = reuters.load_data(num_words=10000)

# نمایش اطلاعات اولیه
print(f"تعداد داده‌های آموزش: {len(train_data)}")
print(f"تعداد داده‌های تست: {len(test_data)}")
print(f"تعداد دسته‌ها (کلاس‌ها): {np.max(train_labels) + 1}")

تعداد داده‌های آموزش: 8982
تعداد داده‌های تست: 2246
تعداد دسته‌ها (کلاس‌ها): 46

فرضیات اولیه و بردارسازی داده‌ها

In [2]:
# بردارسازی داده‌های ورودی (one-hot)
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.0
    return results

x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

# برچسب‌ها به صورت one-hot
from keras.utils import to_categorical

one_hot_train_labels = to_categorical(train_labels)
one_hot_test_labels = to_categorical(test_labels)

 انتخاب معیار موفقیت و تابع زیان

In [3]:
from keras import models, layers

# مدل اولیه ساده‌تر از مدل نهایی
model = models.Sequential()
model.add(layers.Dense(64, activation='relu', input_shape=(10000,)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(46, activation='softmax'))  # 46 دسته خبری

# کامپایل مدل با categorical crossentropy
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

تصمیم‌گیری درباره پروتکل ارزیابی

In [4]:
# تقسیم بخشی از داده‌های آموزش برای اعتبارسنجی
x_val = x_train[:1000]
partial_x_train = x_train[1000:]

y_val = one_hot_train_labels[:1000]
partial_y_train = one_hot_train_labels[1000:]

آماده‌سازی داده‌ها و آموزش مدل پایه

In [5]:
# آموزش مدل پایه با ۲۰ دوره
history = model.fit(partial_x_train,
                    partial_y_train,
                    epochs=20,
                    batch_size=512,
                    validation_data=(x_val, y_val))

Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.4110 - loss: 3.1741 - val_accuracy: 0.6200 - val_loss: 1.7691
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6637 - loss: 1.5976 - val_accuracy: 0.6940 - val_loss: 1.3609
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7367 - loss: 1.2038 - val_accuracy: 0.7310 - val_loss: 1.1869
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7873 - loss: 0.9866 - val_accuracy: 0.7480 - val_loss: 1.0802
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8219 - loss: 0.8131 - val_accuracy: 0.7700 - val_loss: 1.0070
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8562 - loss: 0.6515 - val_accuracy: 0.7860 - val_loss: 0.9604
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8802 - loss: 0.5503 - val_accuracy: 0.7970 - val_loss: 0.9384
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9072 - loss: 0.4412 - val_accuracy: 0.8050 - val_loss: 0.8982
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9207 - loss: 0.3862 - val_accuracy: 0.7960 - val_loss: 0.9167
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9309 - loss: 0.3209 - val_accuracy: 0.8030 - val_loss: 0.8964
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9362 - loss: 0.2752 - val_accuracy: 0.8080 - val_loss: 0.8982
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9446 - loss: 0.2392 - val_accuracy: 0.8220 - val_loss: 0.8643
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9508 - loss: 0.2146 - val_accuracy: 0.8140 - val_loss: 0.8924
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9554 - loss: 0.1913 - val_accuracy: 0.8180 - val_loss: 0.9097
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9505 - loss: 0.1789 - val_accuracy: 0.8170 - val_loss: 0.9210
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9559 - loss: 0.1574 - val_accuracy: 0.8150 - val_loss: 0.9103
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9562 - loss: 0.1489 - val_accuracy: 0.8160 - val_loss: 0.9356
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9570 - loss: 0.1370 - val_accuracy: 0.7980 - val_loss: 1.0137
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9618 - loss: 0.1303 - val_accuracy: 0.8090 - val_loss: 0.9667
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9589 - loss: 0.1245 - val_accuracy: 0.8110 - val_loss: 0.9726

نمایش نمودار دقت و زیان:

In [6]:
import matplotlib.pyplot as plt

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(1, len(acc) + 1)

# نمودار دقت
plt.figure(figsize=(10, 4))

# Accuracy plot
plt.subplot(1, 2, 1)
plt.plot(epochs, acc, color='navy', marker='o', label='Training Accuracy')
plt.plot(epochs, val_acc, color='pink', marker='o', label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss plot
plt.subplot(1, 2, 2)
plt.plot(epochs, loss, color='navy', marker='o', label='Training Loss')
plt.plot(epochs, val_loss, color='pink', marker='o', label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

In [9]:
# مدل با ظرفیت بیشتر برای نمایش overfitting
overfit_model = models.Sequential()
overfit_model.add(layers.Dense(512, activation='relu', input_shape=(10000,)))
overfit_model.add(layers.Dense(512, activation='relu'))
overfit_model.add(layers.Dense(46, activation='softmax'))

overfit_model.compile(optimizer='rmsprop',
                      loss='categorical_crossentropy',
                      metrics=['accuracy'])

overfit_history = overfit_model.fit(partial_x_train, partial_y_train,
                                    epochs=40, batch_size=512,
                                    validation_data=(x_val, y_val))

import matplotlib.pyplot as plt

acc = overfit_history.history['accuracy']
val_acc = overfit_history.history['val_accuracy']
loss = overfit_history.history['loss']
val_loss = overfit_history.history['val_loss']

epochs = range(1, len(acc) + 1)
print(epochs)
# نمودار دقت
plt.figure(figsize=(10, 4))

# Accuracy plot
plt.subplot(1, 2, 1)
plt.plot(epochs, acc, color='deepskyblue', marker='o', label='Training Accuracy')
plt.plot(epochs, val_acc, color='deeppink', marker='o', label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss plot
plt.subplot(1, 2, 2)
plt.plot(epochs, loss, color='deepskyblue', marker='o', label='Training Loss')
plt.plot(epochs, val_loss, color='deeppink', marker='o', label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

Epoch 1/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 73ms/step - accuracy: 0.4091 - loss: 2.5692 - val_accuracy: 0.6610 - val_loss: 1.4114
Epoch 2/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.7247 - loss: 1.1854 - val_accuracy: 0.7580 - val_loss: 1.0572
Epoch 3/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.8093 - loss: 0.8256 - val_accuracy: 0.7760 - val_loss: 0.9700
Epoch 4/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.8743 - loss: 0.5648 - val_accuracy: 0.7900 - val_loss: 0.8920
Epoch 5/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.9058 - loss: 0.3996 - val_accuracy: 0.8110 - val_loss: 0.8790
Epoch 6/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.9327 - loss: 0.2985 - val_accuracy: 0.8230 - val_loss: 0.7826
Epoch 7/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 61ms/step - accuracy: 0.9438 - loss: 0.2216 - val_accuracy: 0.8060 - val_loss: 0.8976
Epoch 8/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 57ms/step - accuracy: 0.9510 - loss: 0.1942 - val_accuracy: 0.8080 - val_loss: 0.8779
Epoch 9/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 62ms/step - accuracy: 0.9564 - loss: 0.1617 - val_accuracy: 0.8110 - val_loss: 0.8838
Epoch 10/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 57ms/step - accuracy: 0.9631 - loss: 0.1325 - val_accuracy: 0.8190 - val_loss: 0.8481
Epoch 11/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.9502 - loss: 0.1671 - val_accuracy: 0.8060 - val_loss: 0.8671
Epoch 12/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.9604 - loss: 0.1256 - val_accuracy: 0.7960 - val_loss: 0.9376
Epoch 13/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.9629 - loss: 0.1086 - val_accuracy: 0.8180 - val_loss: 0.8925
Epoch 14/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.9611 - loss: 0.1122 - val_accuracy: 0.8140 - val_loss: 0.8889
Epoch 15/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.9578 - loss: 0.1114 - val_accuracy: 0.8010 - val_loss: 0.9600
Epoch 16/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.9636 - loss: 0.1017 - val_accuracy: 0.8090 - val_loss: 0.8994
Epoch 17/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.9633 - loss: 0.0951 - val_accuracy: 0.7960 - val_loss: 0.9635
Epoch 18/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 57ms/step - accuracy: 0.9649 - loss: 0.0927 - val_accuracy: 0.8060 - val_loss: 0.8995
Epoch 19/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.9635 - loss: 0.0974 - val_accuracy: 0.8090 - val_loss: 0.9297
Epoch 20/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.9624 - loss: 0.0954 - val_accuracy: 0.7980 - val_loss: 0.9817
Epoch 21/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.9621 - loss: 0.0943 - val_accuracy: 0.8160 - val_loss: 0.8925
Epoch 22/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.9629 - loss: 0.0871 - val_accuracy: 0.8080 - val_loss: 0.9159
Epoch 23/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.9652 - loss: 0.0834 - val_accuracy: 0.8100 - val_loss: 0.9347
Epoch 24/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.9648 - loss: 0.0780 - val_accuracy: 0.8170 - val_loss: 0.8977
Epoch 25/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.9571 - loss: 0.0937 - val_accuracy: 0.8090 - val_loss: 0.9338
Epoch 26/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.9627 - loss: 0.0825 - val_accuracy: 0.8040 - val_loss: 0.9755
Epoch 27/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.9620 - loss: 0.0816 - val_accuracy: 0.7960 - val_loss: 1.0552
Epoch 28/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.9616 - loss: 0.0851 - val_accuracy: 0.8190 - val_loss: 0.9038
Epoch 29/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.9643 - loss: 0.0766 - val_accuracy: 0.7940 - val_loss: 1.0071
Epoch 30/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.9637 - loss: 0.0774 - val_accuracy: 0.7850 - val_loss: 1.0656
Epoch 31/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - accuracy: 0.9611 - loss: 0.0854 - val_accuracy: 0.8240 - val_loss: 0.8827
Epoch 32/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.9606 - loss: 0.0766 - val_accuracy: 0.8230 - val_loss: 0.9154
Epoch 33/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.9649 - loss: 0.0694 - val_accuracy: 0.8100 - val_loss: 0.9560
Epoch 34/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 57ms/step - accuracy: 0.9627 - loss: 0.0758 - val_accuracy: 0.8070 - val_loss: 0.9676
Epoch 35/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 61ms/step - accuracy: 0.9628 - loss: 0.0748 - val_accuracy: 0.7910 - val_loss: 1.0632
Epoch 36/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 57ms/step - accuracy: 0.9601 - loss: 0.0803 - val_accuracy: 0.8170 - val_loss: 0.9132
Epoch 37/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 57ms/step - accuracy: 0.9621 - loss: 0.0747 - val_accuracy: 0.8120 - val_loss: 0.9537
Epoch 38/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.9658 - loss: 0.0691 - val_accuracy: 0.8090 - val_loss: 0.9783
Epoch 39/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - accuracy: 0.9624 - loss: 0.0721 - val_accuracy: 0.8120 - val_loss: 0.9797
Epoch 40/40
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - accuracy: 0.9633 - loss: 0.0686 - val_accuracy: 0.8050 - val_loss: 0.9556
range(1, 41)

 افزایش پیچیدگی و مشاهده overfitting

In [10]:
# مدل با ظرفیت بیشتر برای نمایش overfitting
overfit_model = models.Sequential()
overfit_model.add(layers.Dense(128, activation='relu', input_shape=(10000,)))
overfit_model.add(layers.Dense(128, activation='relu'))
overfit_model.add(layers.Dense(46, activation='softmax'))

overfit_model.compile(optimizer='rmsprop',
                      loss='categorical_crossentropy',
                      metrics=['accuracy'])

overfit_history = overfit_model.fit(partial_x_train, partial_y_train,
                                    epochs=30, batch_size=512,
                                    validation_data=(x_val, y_val))

import matplotlib.pyplot as plt

acc = overfit_history.history['accuracy']
val_acc = overfit_history.history['val_accuracy']
loss = overfit_history.history['loss']
val_loss = overfit_history.history['val_loss']

epochs = range(1, len(acc) + 1)

# نمودار دقت
plt.figure(figsize=(10, 4))

# Accuracy plot
plt.subplot(1, 2, 1)
plt.plot(epochs, acc, color='deepskyblue', marker='o', label='Training Accuracy')
plt.plot(epochs, val_acc, color='deeppink', marker='o', label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss plot
plt.subplot(1, 2, 2)
plt.plot(epochs, loss, color='deepskyblue', marker='o', label='Training Loss')
plt.plot(epochs, val_loss, color='deeppink', marker='o', label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

Epoch 1/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.3739 - loss: 2.9431 - val_accuracy: 0.6630 - val_loss: 1.5405
Epoch 2/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6913 - loss: 1.3967 - val_accuracy: 0.7130 - val_loss: 1.2364
Epoch 3/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7753 - loss: 1.0180 - val_accuracy: 0.7700 - val_loss: 1.0796
Epoch 4/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8349 - loss: 0.7669 - val_accuracy: 0.7930 - val_loss: 0.9672
Epoch 5/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8708 - loss: 0.6079 - val_accuracy: 0.8020 - val_loss: 0.9054
Epoch 6/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8931 - loss: 0.4871 - val_accuracy: 0.7920 - val_loss: 0.9078
Epoch 7/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9250 - loss: 0.3651 - val_accuracy: 0.8090 - val_loss: 0.8622
Epoch 8/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9336 - loss: 0.3087 - val_accuracy: 0.8140 - val_loss: 0.8853
Epoch 9/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9428 - loss: 0.2624 - val_accuracy: 0.8020 - val_loss: 0.9213
Epoch 10/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9478 - loss: 0.2248 - val_accuracy: 0.7930 - val_loss: 0.9097
Epoch 11/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9515 - loss: 0.2032 - val_accuracy: 0.8220 - val_loss: 0.8887
Epoch 12/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9563 - loss: 0.1715 - val_accuracy: 0.8120 - val_loss: 0.9154
Epoch 13/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9608 - loss: 0.1491 - val_accuracy: 0.7950 - val_loss: 0.9479
Epoch 14/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9577 - loss: 0.1474 - val_accuracy: 0.8050 - val_loss: 0.9852
Epoch 15/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9604 - loss: 0.1388 - val_accuracy: 0.7790 - val_loss: 1.0253
Epoch 16/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9597 - loss: 0.1361 - val_accuracy: 0.8030 - val_loss: 0.9917
Epoch 17/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9634 - loss: 0.1201 - val_accuracy: 0.8100 - val_loss: 0.9618
Epoch 18/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9624 - loss: 0.1146 - val_accuracy: 0.7900 - val_loss: 1.0715
Epoch 19/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9611 - loss: 0.1236 - val_accuracy: 0.8070 - val_loss: 0.9608
Epoch 20/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9601 - loss: 0.1122 - val_accuracy: 0.8130 - val_loss: 0.9811
Epoch 21/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9596 - loss: 0.1145 - val_accuracy: 0.8150 - val_loss: 0.9365
Epoch 22/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9633 - loss: 0.1040 - val_accuracy: 0.8080 - val_loss: 0.9754
Epoch 23/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9626 - loss: 0.1024 - val_accuracy: 0.8010 - val_loss: 0.9980
Epoch 24/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9615 - loss: 0.1130 - val_accuracy: 0.8130 - val_loss: 0.9745
Epoch 25/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9603 - loss: 0.0987 - val_accuracy: 0.8060 - val_loss: 1.0006
Epoch 26/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9618 - loss: 0.0945 - val_accuracy: 0.8100 - val_loss: 0.9828
Epoch 27/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9644 - loss: 0.0924 - val_accuracy: 0.8140 - val_loss: 1.0022
Epoch 28/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9621 - loss: 0.1028 - val_accuracy: 0.8110 - val_loss: 0.9950
Epoch 29/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9641 - loss: 0.0887 - val_accuracy: 0.8110 - val_loss: 0.9914
Epoch 30/30
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9630 - loss: 0.0929 - val_accuracy: 0.8120 - val_loss: 0.9920

اعمال Regularization و تنظیم ابرپارامترها

L2 Regularization

In [16]:
import tensorflow as tf
from tensorflow.keras import models, layers, regularizers
import matplotlib.pyplot as plt
import numpy as np

# فرض می‌کنیم partial_x_train, partial_y_train, x_val, y_val از قبل تعریف شده‌اند

# لیست مقادیر مختلف L2
l2_values = [0.0001, 0.01, 0.001]

# ذخیره تاریخچه‌ها و بهترین دقت اعتبارسنجی برای هر مقدار L2
histories = {}
best_val_accuracies = {}

# حلقه برای آزمایش مقادیر مختلف L2
for l2_val in l2_values:
    print(f"\nTraining model with L2={l2_val}")
    
    # تعریف مدل
    l2_model = models.Sequential()
    l2_model.add(layers.Dense(64, activation='relu',
                             kernel_regularizer=regularizers.l2(l2_val),
                             input_shape=(10000,)))
    l2_model.add(layers.Dense(64, activation='relu',
                             kernel_regularizer=regularizers.l2(l2_val)))
    l2_model.add(layers.Dense(46, activation='softmax'))

    # کامپایل مدل
    l2_model.compile(optimizer='rmsprop',
                    loss='categorical_crossentropy',
                    metrics=['accuracy'])

    # آموزش مدل
    history = l2_model.fit(partial_x_train, partial_y_train,
                          epochs=20, batch_size=512,
                          validation_data=(x_val, y_val),
                          verbose=1)
    
    # ذخیره تاریخچه
    histories[l2_val] = history.history
    
    # ذخیره بهترین دقت اعتبارسنجی
    best_val_accuracies[l2_val] = max(history.history['val_accuracy'])

# پیدا کردن بهترین مقدار L2
best_l2 = max(best_val_accuracies, key=best_val_accuracies.get)
print(f"\nBest L2 value: {best_l2} with validation accuracy: {best_val_accuracies[best_l2]:.4f}")

# رسم نمودارهای جداگانه برای هر مقدار L2
for l2_val in l2_values:
    history = histories[l2_val]
    
    plt.figure(figsize=(12, 4))
    
    # نمودار دقت
    plt.subplot(1, 2, 1)
    plt.plot(history['accuracy'], label='Train Accuracy')
    plt.plot(history['val_accuracy'], '--', label='Validation Accuracy')
    plt.title(f'Accuracy (L2={l2_val})')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)
    
    # نمودار خطا
    plt.subplot(1, 2, 2)
    plt.plot(history['loss'], label='Train Loss')
    plt.plot(history['val_loss'], '--', label='Validation Loss')
    plt.title(f'Loss (L2={l2_val})')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    
    plt.tight_layout()
    plt.show()

# رسم نمودار مقایسه‌ای برای همه مقادیر L2
plt.figure(figsize=(12, 8))

# نمودار دقت اعتبارسنجی
plt.subplot(2, 1, 1)
for l2_val in l2_values:
    plt.plot(histories[l2_val]['val_accuracy'], label=f'Val Acc (L2={l2_val})')
plt.title('Validation Accuracy Comparison for Different L2 Values')
plt.xlabel('Epoch')
plt.ylabel('Validation Accuracy')
plt.legend()
plt.grid(True)

# نمودار خطای اعتبارسنجی
plt.subplot(2, 1, 2)
for l2_val in l2_values:
    plt.plot(histories[l2_val]['val_loss'], label=f'Val Loss (L2={l2_val})')
plt.title('Validation Loss Comparison for Different L2 Values')
plt.xlabel('Epoch')
plt.ylabel('Validation Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

Training model with L2=0.0001
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.3918 - loss: 3.2232 - val_accuracy: 0.6350 - val_loss: 1.8778
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6743 - loss: 1.6716 - val_accuracy: 0.6830 - val_loss: 1.4259
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7274 - loss: 1.2488 - val_accuracy: 0.7290 - val_loss: 1.2225
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7911 - loss: 0.9954 - val_accuracy: 0.7540 - val_loss: 1.1208
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8133 - loss: 0.8710 - val_accuracy: 0.7780 - val_loss: 1.0376
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8449 - loss: 0.7287 - val_accuracy: 0.7810 - val_loss: 1.0036
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8677 - loss: 0.6458 - val_accuracy: 0.8070 - val_loss: 0.9603
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8965 - loss: 0.5260 - val_accuracy: 0.8100 - val_loss: 0.9412
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9062 - loss: 0.4560 - val_accuracy: 0.8190 - val_loss: 0.9128
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9244 - loss: 0.3849 - val_accuracy: 0.8010 - val_loss: 0.9480
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9328 - loss: 0.3497 - val_accuracy: 0.8140 - val_loss: 0.9171
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9438 - loss: 0.3016 - val_accuracy: 0.8160 - val_loss: 0.9247
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9499 - loss: 0.2729 - val_accuracy: 0.8110 - val_loss: 0.9316
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9529 - loss: 0.2474 - val_accuracy: 0.8120 - val_loss: 0.9614
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9534 - loss: 0.2306 - val_accuracy: 0.8260 - val_loss: 0.9160
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9516 - loss: 0.2209 - val_accuracy: 0.8120 - val_loss: 0.9763
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9578 - loss: 0.2040 - val_accuracy: 0.8060 - val_loss: 0.9693
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9591 - loss: 0.1962 - val_accuracy: 0.8170 - val_loss: 0.9875
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9581 - loss: 0.1900 - val_accuracy: 0.8150 - val_loss: 0.9731
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9616 - loss: 0.1731 - val_accuracy: 0.8160 - val_loss: 1.0163

Training model with L2=0.01
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.3344 - loss: 4.9001 - val_accuracy: 0.5770 - val_loss: 3.0188
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6176 - loss: 2.7772 - val_accuracy: 0.6640 - val_loss: 2.2491
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6880 - loss: 2.1408 - val_accuracy: 0.6960 - val_loss: 1.9977
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7141 - loss: 1.9050 - val_accuracy: 0.7110 - val_loss: 1.8905
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7314 - loss: 1.7917 - val_accuracy: 0.7120 - val_loss: 1.8002
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7462 - loss: 1.6743 - val_accuracy: 0.7200 - val_loss: 1.7411
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7429 - loss: 1.6597 - val_accuracy: 0.7310 - val_loss: 1.6930
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7659 - loss: 1.5651 - val_accuracy: 0.7100 - val_loss: 1.7119
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7703 - loss: 1.5427 - val_accuracy: 0.7460 - val_loss: 1.6318
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7791 - loss: 1.4873 - val_accuracy: 0.7360 - val_loss: 1.6211
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7836 - loss: 1.4633 - val_accuracy: 0.7520 - val_loss: 1.5676
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7903 - loss: 1.4268 - val_accuracy: 0.7440 - val_loss: 1.5528
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7946 - loss: 1.3861 - val_accuracy: 0.7470 - val_loss: 1.5517
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8013 - loss: 1.3761 - val_accuracy: 0.7570 - val_loss: 1.5187
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8072 - loss: 1.3185 - val_accuracy: 0.7600 - val_loss: 1.5164
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8072 - loss: 1.3166 - val_accuracy: 0.7750 - val_loss: 1.5026
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8155 - loss: 1.3071 - val_accuracy: 0.7620 - val_loss: 1.4845
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8141 - loss: 1.2720 - val_accuracy: 0.7730 - val_loss: 1.4750
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8180 - loss: 1.2666 - val_accuracy: 0.7710 - val_loss: 1.4942
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8168 - loss: 1.2555 - val_accuracy: 0.7630 - val_loss: 1.4910

Training model with L2=0.001
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.3764 - loss: 3.4143 - val_accuracy: 0.6170 - val_loss: 2.0847
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6517 - loss: 1.8656 - val_accuracy: 0.6920 - val_loss: 1.5902
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7348 - loss: 1.4543 - val_accuracy: 0.7300 - val_loss: 1.3994
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7741 - loss: 1.2385 - val_accuracy: 0.7510 - val_loss: 1.2981
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8100 - loss: 1.0650 - val_accuracy: 0.7890 - val_loss: 1.2370
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8317 - loss: 0.9729 - val_accuracy: 0.7660 - val_loss: 1.2176
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8536 - loss: 0.8795 - val_accuracy: 0.7770 - val_loss: 1.1848
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8713 - loss: 0.8029 - val_accuracy: 0.7930 - val_loss: 1.1479
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8875 - loss: 0.7412 - val_accuracy: 0.8060 - val_loss: 1.1095
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9060 - loss: 0.6703 - val_accuracy: 0.8080 - val_loss: 1.1047
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9182 - loss: 0.6171 - val_accuracy: 0.8000 - val_loss: 1.1117
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9251 - loss: 0.5892 - val_accuracy: 0.8040 - val_loss: 1.1085
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9331 - loss: 0.5571 - val_accuracy: 0.7980 - val_loss: 1.1150
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9330 - loss: 0.5380 - val_accuracy: 0.8080 - val_loss: 1.1121
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9413 - loss: 0.5153 - val_accuracy: 0.8160 - val_loss: 1.0906
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9435 - loss: 0.4960 - val_accuracy: 0.7940 - val_loss: 1.1366
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9467 - loss: 0.4799 - val_accuracy: 0.8110 - val_loss: 1.0963
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9525 - loss: 0.4542 - val_accuracy: 0.7990 - val_loss: 1.1682
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9549 - loss: 0.4456 - val_accuracy: 0.8080 - val_loss: 1.1033
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9537 - loss: 0.4367 - val_accuracy: 0.8040 - val_loss: 1.1252

Best L2 value: 0.0001 with validation accuracy: 0.8260

L2 Regularization + Dropout

In [17]:
import tensorflow as tf
from tensorflow.keras import models, layers, regularizers
import matplotlib.pyplot as plt
import numpy as np

# فرض می‌کنیم partial_x_train, partial_y_train, x_val, y_val از قبل تعریف شده‌اند

# لیست مقادیر مختلف L2 و Dropout
l2_values = [0.0001, 0.001, 0.01, 0.1]
dropout_rates = [0.3, 0.5, 0.7]

# ذخیره تاریخچه‌ها و بهترین دقت اعتبارسنجی برای هر ترکیب
histories = {}
best_val_accuracies = {}

# حلقه برای آزمایش ترکیب‌های مختلف L2 و Dropout
for l2_val in l2_values:
    for dropout_rate in dropout_rates:
        combo_key = f"L2={l2_val}, Dropout={dropout_rate}"
        print(f"\nTraining model with {combo_key}")
        
        # تعریف مدل
        combo_model = models.Sequential()
        combo_model.add(layers.Dense(64, activation='relu',
                                    kernel_regularizer=regularizers.l2(l2_val),
                                    input_shape=(10000,)))
        combo_model.add(layers.Dropout(dropout_rate))
        combo_model.add(layers.Dense(64, activation='relu',
                                    kernel_regularizer=regularizers.l2(l2_val)))
        combo_model.add(layers.Dropout(dropout_rate))
        combo_model.add(layers.Dense(46, activation='softmax'))

        # کامپایل مدل
        combo_model.compile(optimizer='rmsprop',
                           loss='categorical_crossentropy',
                           metrics=['accuracy'])

        # آموزش مدل
        history = combo_model.fit(partial_x_train, partial_y_train,
                                 epochs=20, batch_size=512,
                                 validation_data=(x_val, y_val),
                                 verbose=1)
        
        # ذخیره تاریخچه
        histories[combo_key] = history.history
        
        # ذخیره بهترین دقت اعتبارسنجی
        best_val_accuracies[combo_key] = max(history.history['val_accuracy'])

# پیدا کردن بهترین ترکیب
best_combo = max(best_val_accuracies, key=best_val_accuracies.get)
print(f"\nBest combination: {best_combo} with validation accuracy: {best_val_accuracies[best_combo]:.4f}")

# رسم نمودارهای جداگانه برای هر ترکیب
for combo_key in histories:
    history = histories[combo_key]
    
    plt.figure(figsize=(12, 4))
    
    # نمودار دقت
    plt.subplot(1, 2, 1)
    plt.plot(history['accuracy'], label='Train Accuracy')
    plt.plot(history['val_accuracy'], '--', label='Validation Accuracy')
    plt.title(f'Accuracy ({combo_key})')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)
    
    # نمودار خطا
    plt.subplot(1, 2, 2)
    plt.plot(history['loss'], label='Train Loss')
    plt.plot(history['val_loss'], '--', label='Validation Loss')
    plt.title(f'Loss ({combo_key})')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    
    plt.tight_layout()
    plt.show()

# رسم نمودار مقایسه‌ای برای همه ترکیب‌ها
plt.figure(figsize=(12, 8))

# نمودار دقت اعتبارسنجی
plt.subplot(2, 1, 1)
for combo_key in histories:
    plt.plot(histories[combo_key]['val_accuracy'], label=combo_key)
plt.title('Validation Accuracy Comparison for Different L2 and Dropout Combinations')
plt.xlabel('Epoch')
plt.ylabel('Validation Accuracy')
plt.legend()
plt.grid(True)

# نمودار خطای اعتبارسنجی
plt.subplot(2, 1, 2)
for combo_key in histories:
    plt.plot(histories[combo_key]['val_loss'], label=combo_key)
plt.title('Validation Loss Comparison for Different L2 and Dropout Combinations')
plt.xlabel('Epoch')
plt.ylabel('Validation Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

Training model with L2=0.0001, Dropout=0.3
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.2903 - loss: 3.4024 - val_accuracy: 0.5960 - val_loss: 2.0169
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5816 - loss: 1.9816 - val_accuracy: 0.6560 - val_loss: 1.5279
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6596 - loss: 1.5826 - val_accuracy: 0.6950 - val_loss: 1.3240
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6968 - loss: 1.3295 - val_accuracy: 0.7190 - val_loss: 1.2228
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7192 - loss: 1.2223 - val_accuracy: 0.7330 - val_loss: 1.1567
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7449 - loss: 1.1075 - val_accuracy: 0.7570 - val_loss: 1.0990
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7689 - loss: 1.0090 - val_accuracy: 0.7610 - val_loss: 1.0625
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7928 - loss: 0.9068 - val_accuracy: 0.7730 - val_loss: 1.0209
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8078 - loss: 0.8466 - val_accuracy: 0.7910 - val_loss: 0.9890
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8318 - loss: 0.7681 - val_accuracy: 0.7960 - val_loss: 0.9735
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8364 - loss: 0.7252 - val_accuracy: 0.8000 - val_loss: 0.9608
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8468 - loss: 0.6810 - val_accuracy: 0.8010 - val_loss: 0.9479
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8685 - loss: 0.6103 - val_accuracy: 0.8090 - val_loss: 0.9268
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8721 - loss: 0.5735 - val_accuracy: 0.8100 - val_loss: 0.9302
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8776 - loss: 0.5294 - val_accuracy: 0.8090 - val_loss: 0.9299
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8899 - loss: 0.4903 - val_accuracy: 0.8200 - val_loss: 0.9170
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8973 - loss: 0.4654 - val_accuracy: 0.8110 - val_loss: 0.9352
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8962 - loss: 0.4494 - val_accuracy: 0.8130 - val_loss: 0.9269
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9021 - loss: 0.4415 - val_accuracy: 0.8230 - val_loss: 0.9138
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9151 - loss: 0.3898 - val_accuracy: 0.8200 - val_loss: 0.9274

Training model with L2=0.0001, Dropout=0.5
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.2019 - loss: 3.5104 - val_accuracy: 0.5520 - val_loss: 2.2038
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5138 - loss: 2.2501 - val_accuracy: 0.6160 - val_loss: 1.6612
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5756 - loss: 1.8447 - val_accuracy: 0.6740 - val_loss: 1.4754
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6203 - loss: 1.5995 - val_accuracy: 0.6890 - val_loss: 1.3691
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6467 - loss: 1.4924 - val_accuracy: 0.7060 - val_loss: 1.2947
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6858 - loss: 1.3493 - val_accuracy: 0.7200 - val_loss: 1.2387
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6882 - loss: 1.3392 - val_accuracy: 0.7350 - val_loss: 1.1959
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7160 - loss: 1.1929 - val_accuracy: 0.7440 - val_loss: 1.1643
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7287 - loss: 1.1359 - val_accuracy: 0.7580 - val_loss: 1.1390
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7391 - loss: 1.1094 - val_accuracy: 0.7560 - val_loss: 1.1196
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7660 - loss: 1.0075 - val_accuracy: 0.7620 - val_loss: 1.0923
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7595 - loss: 1.0029 - val_accuracy: 0.7680 - val_loss: 1.0823
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7737 - loss: 0.9589 - val_accuracy: 0.7720 - val_loss: 1.0642
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7844 - loss: 0.9041 - val_accuracy: 0.7740 - val_loss: 1.0580
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7871 - loss: 0.8842 - val_accuracy: 0.7790 - val_loss: 1.0551
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8023 - loss: 0.8162 - val_accuracy: 0.7770 - val_loss: 1.0462
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8016 - loss: 0.8085 - val_accuracy: 0.7870 - val_loss: 1.0387
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8087 - loss: 0.7849 - val_accuracy: 0.7830 - val_loss: 1.0395
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8139 - loss: 0.7655 - val_accuracy: 0.7880 - val_loss: 1.0437
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8255 - loss: 0.7259 - val_accuracy: 0.7920 - val_loss: 1.0398

Training model with L2=0.0001, Dropout=0.7
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.0939 - loss: 3.6669 - val_accuracy: 0.4130 - val_loss: 2.7050
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3505 - loss: 2.8383 - val_accuracy: 0.5640 - val_loss: 2.0621
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4554 - loss: 2.3318 - val_accuracy: 0.5880 - val_loss: 1.7689
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4821 - loss: 2.1375 - val_accuracy: 0.6280 - val_loss: 1.6429
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5321 - loss: 1.9152 - val_accuracy: 0.6650 - val_loss: 1.5683
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5648 - loss: 1.8088 - val_accuracy: 0.6800 - val_loss: 1.5066
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5885 - loss: 1.7047 - val_accuracy: 0.6940 - val_loss: 1.4538
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6029 - loss: 1.6405 - val_accuracy: 0.6990 - val_loss: 1.4262
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6087 - loss: 1.6322 - val_accuracy: 0.7020 - val_loss: 1.3850
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6161 - loss: 1.5852 - val_accuracy: 0.7070 - val_loss: 1.3560
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6374 - loss: 1.4992 - val_accuracy: 0.7080 - val_loss: 1.3258
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6475 - loss: 1.4631 - val_accuracy: 0.7090 - val_loss: 1.3155
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6561 - loss: 1.4387 - val_accuracy: 0.7080 - val_loss: 1.3035
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6627 - loss: 1.3725 - val_accuracy: 0.7170 - val_loss: 1.2828
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6677 - loss: 1.3621 - val_accuracy: 0.7150 - val_loss: 1.2761
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6757 - loss: 1.3346 - val_accuracy: 0.7180 - val_loss: 1.2686
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6796 - loss: 1.3332 - val_accuracy: 0.7200 - val_loss: 1.2716
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6836 - loss: 1.2749 - val_accuracy: 0.7170 - val_loss: 1.2656
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6891 - loss: 1.2790 - val_accuracy: 0.7240 - val_loss: 1.2641
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6983 - loss: 1.2330 - val_accuracy: 0.7260 - val_loss: 1.2682

Training model with L2=0.001, Dropout=0.3
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.2754 - loss: 3.5660 - val_accuracy: 0.5710 - val_loss: 2.2003
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5685 - loss: 2.1614 - val_accuracy: 0.6560 - val_loss: 1.6960
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6383 - loss: 1.7832 - val_accuracy: 0.6950 - val_loss: 1.5082
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6866 - loss: 1.5492 - val_accuracy: 0.7110 - val_loss: 1.4015
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7216 - loss: 1.3620 - val_accuracy: 0.7250 - val_loss: 1.3274
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7491 - loss: 1.2573 - val_accuracy: 0.7610 - val_loss: 1.2653
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7712 - loss: 1.1799 - val_accuracy: 0.7720 - val_loss: 1.2143
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7853 - loss: 1.1049 - val_accuracy: 0.7880 - val_loss: 1.1846
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8093 - loss: 1.0239 - val_accuracy: 0.7950 - val_loss: 1.1545
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8189 - loss: 0.9770 - val_accuracy: 0.8020 - val_loss: 1.1409
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8258 - loss: 0.9338 - val_accuracy: 0.7960 - val_loss: 1.1330
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8407 - loss: 0.8782 - val_accuracy: 0.8030 - val_loss: 1.1169
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8410 - loss: 0.8504 - val_accuracy: 0.8090 - val_loss: 1.1061
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8499 - loss: 0.8176 - val_accuracy: 0.8090 - val_loss: 1.1050
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8669 - loss: 0.7565 - val_accuracy: 0.8110 - val_loss: 1.0961
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8770 - loss: 0.7415 - val_accuracy: 0.8100 - val_loss: 1.1000
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8800 - loss: 0.7270 - val_accuracy: 0.8120 - val_loss: 1.0960
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8875 - loss: 0.6899 - val_accuracy: 0.8110 - val_loss: 1.0933
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8891 - loss: 0.6830 - val_accuracy: 0.8110 - val_loss: 1.0881
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8872 - loss: 0.6832 - val_accuracy: 0.8130 - val_loss: 1.0943

Training model with L2=0.001, Dropout=0.5
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.2382 - loss: 3.5700 - val_accuracy: 0.5430 - val_loss: 2.2456
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4969 - loss: 2.3815 - val_accuracy: 0.5990 - val_loss: 1.8281
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5626 - loss: 1.9997 - val_accuracy: 0.6600 - val_loss: 1.6385
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6192 - loss: 1.7737 - val_accuracy: 0.6980 - val_loss: 1.5275
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6481 - loss: 1.6456 - val_accuracy: 0.7060 - val_loss: 1.4504
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6811 - loss: 1.5246 - val_accuracy: 0.7170 - val_loss: 1.3935
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6887 - loss: 1.4567 - val_accuracy: 0.7260 - val_loss: 1.3449
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7118 - loss: 1.3793 - val_accuracy: 0.7360 - val_loss: 1.3003
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7274 - loss: 1.3058 - val_accuracy: 0.7360 - val_loss: 1.2774
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7353 - loss: 1.2419 - val_accuracy: 0.7530 - val_loss: 1.2573
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7440 - loss: 1.2353 - val_accuracy: 0.7620 - val_loss: 1.2455
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7519 - loss: 1.1738 - val_accuracy: 0.7710 - val_loss: 1.2175
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7620 - loss: 1.1276 - val_accuracy: 0.7680 - val_loss: 1.2151
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7735 - loss: 1.1021 - val_accuracy: 0.7760 - val_loss: 1.1946
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7766 - loss: 1.0733 - val_accuracy: 0.7790 - val_loss: 1.1855
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8021 - loss: 1.0176 - val_accuracy: 0.7770 - val_loss: 1.1970
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7906 - loss: 1.0216 - val_accuracy: 0.7760 - val_loss: 1.1916
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7930 - loss: 0.9957 - val_accuracy: 0.7820 - val_loss: 1.1836
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7990 - loss: 0.9897 - val_accuracy: 0.7810 - val_loss: 1.1646
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8068 - loss: 0.9488 - val_accuracy: 0.7900 - val_loss: 1.1697

Training model with L2=0.001, Dropout=0.7
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.1185 - loss: 3.8296 - val_accuracy: 0.3700 - val_loss: 2.8684
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3406 - loss: 2.9630 - val_accuracy: 0.5310 - val_loss: 2.2253
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4233 - loss: 2.4924 - val_accuracy: 0.5740 - val_loss: 1.9523
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4776 - loss: 2.2613 - val_accuracy: 0.6150 - val_loss: 1.8033
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5056 - loss: 2.1161 - val_accuracy: 0.6440 - val_loss: 1.7083
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5552 - loss: 1.9389 - val_accuracy: 0.6570 - val_loss: 1.6418
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5511 - loss: 1.9382 - val_accuracy: 0.6790 - val_loss: 1.6028
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5858 - loss: 1.8079 - val_accuracy: 0.6830 - val_loss: 1.5504
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6010 - loss: 1.7404 - val_accuracy: 0.6910 - val_loss: 1.5227
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6161 - loss: 1.7057 - val_accuracy: 0.6920 - val_loss: 1.5005
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6227 - loss: 1.6347 - val_accuracy: 0.6970 - val_loss: 1.4686
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6310 - loss: 1.5970 - val_accuracy: 0.7010 - val_loss: 1.4580
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6335 - loss: 1.5909 - val_accuracy: 0.7010 - val_loss: 1.4273
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6379 - loss: 1.5699 - val_accuracy: 0.7070 - val_loss: 1.4183
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6512 - loss: 1.5275 - val_accuracy: 0.7040 - val_loss: 1.3984
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6601 - loss: 1.4843 - val_accuracy: 0.7080 - val_loss: 1.3857
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6645 - loss: 1.4614 - val_accuracy: 0.7090 - val_loss: 1.3737
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6612 - loss: 1.4610 - val_accuracy: 0.7080 - val_loss: 1.3729
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6806 - loss: 1.3911 - val_accuracy: 0.7100 - val_loss: 1.3689
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6700 - loss: 1.4099 - val_accuracy: 0.7080 - val_loss: 1.3594

Training model with L2=0.01, Dropout=0.3
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.3406 - loss: 4.8437 - val_accuracy: 0.5650 - val_loss: 2.8827
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5669 - loss: 2.7878 - val_accuracy: 0.6210 - val_loss: 2.2832
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6126 - loss: 2.3365 - val_accuracy: 0.6720 - val_loss: 2.0484
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6623 - loss: 2.0693 - val_accuracy: 0.6880 - val_loss: 1.9368
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6923 - loss: 1.9200 - val_accuracy: 0.6920 - val_loss: 1.8386
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6970 - loss: 1.8490 - val_accuracy: 0.7010 - val_loss: 1.7737
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7113 - loss: 1.7555 - val_accuracy: 0.7090 - val_loss: 1.7189
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7149 - loss: 1.6915 - val_accuracy: 0.7210 - val_loss: 1.6643
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7183 - loss: 1.6565 - val_accuracy: 0.7210 - val_loss: 1.6332
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7274 - loss: 1.5957 - val_accuracy: 0.7060 - val_loss: 1.6086
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7217 - loss: 1.5795 - val_accuracy: 0.7220 - val_loss: 1.5653
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7338 - loss: 1.5219 - val_accuracy: 0.7310 - val_loss: 1.5349
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7383 - loss: 1.5085 - val_accuracy: 0.7340 - val_loss: 1.5170
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7449 - loss: 1.4702 - val_accuracy: 0.7190 - val_loss: 1.5268
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7537 - loss: 1.4377 - val_accuracy: 0.7440 - val_loss: 1.4853
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7518 - loss: 1.4398 - val_accuracy: 0.7410 - val_loss: 1.4713
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7592 - loss: 1.4050 - val_accuracy: 0.7500 - val_loss: 1.4563
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7580 - loss: 1.3901 - val_accuracy: 0.7370 - val_loss: 1.4650
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7636 - loss: 1.3786 - val_accuracy: 0.7560 - val_loss: 1.4429
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7655 - loss: 1.3572 - val_accuracy: 0.7360 - val_loss: 1.4464

Training model with L2=0.01, Dropout=0.5
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.1586 - loss: 5.0357 - val_accuracy: 0.5440 - val_loss: 3.2016
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4672 - loss: 3.1996 - val_accuracy: 0.5800 - val_loss: 2.3999
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5473 - loss: 2.5586 - val_accuracy: 0.6250 - val_loss: 2.1359
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5973 - loss: 2.2871 - val_accuracy: 0.6610 - val_loss: 2.0003
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6238 - loss: 2.1243 - val_accuracy: 0.6800 - val_loss: 1.9103
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6420 - loss: 2.0244 - val_accuracy: 0.6890 - val_loss: 1.8354
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6629 - loss: 1.9102 - val_accuracy: 0.6930 - val_loss: 1.7724
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6696 - loss: 1.8390 - val_accuracy: 0.6980 - val_loss: 1.7163
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6739 - loss: 1.8069 - val_accuracy: 0.6990 - val_loss: 1.6792
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6863 - loss: 1.7510 - val_accuracy: 0.7150 - val_loss: 1.6390
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6891 - loss: 1.7255 - val_accuracy: 0.7010 - val_loss: 1.6239
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7013 - loss: 1.6558 - val_accuracy: 0.7050 - val_loss: 1.5869
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6924 - loss: 1.6479 - val_accuracy: 0.7110 - val_loss: 1.5609
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7055 - loss: 1.6071 - val_accuracy: 0.6990 - val_loss: 1.5513
Epoch 15/20

L1-L2 Regularization

In [20]:
import tensorflow as tf
from tensorflow.keras import models, layers, regularizers
import matplotlib.pyplot as plt
import numpy as np

# فرض می‌کنیم partial_x_train, partial_y_train, x_val, y_val از قبل تعریف شده‌اند

# لیست مقادیر مختلف L1 و L2
l1_values = [0.0001, 0.001, 0.01]
l2_values = [0.0001, 0.001, 0.01]

# ذخیره تاریخچه‌ها و بهترین دقت اعتبارسنجی برای هر ترکیب
histories = {}
best_val_accuracies = {}

# حلقه برای آزمایش ترکیب‌های مختلف L1 و L2
for l1_val in l1_values:
    for l2_val in l2_values:
        combo_key = f"L1={l1_val}, L2={l2_val}"
        print(f"\nTraining model with {combo_key}")
        
        # تعریف مدل
        elastic_model = models.Sequential()
        elastic_model.add(layers.Dense(64, activation='relu',
                                      kernel_regularizer=regularizers.l1_l2(l1=l1_val, l2=l2_val),
                                      input_shape=(10000,)))
        elastic_model.add(layers.Dense(64, activation='relu',
                                      kernel_regularizer=regularizers.l1_l2(l1=l1_val, l2=l2_val)))
        elastic_model.add(layers.Dense(46, activation='softmax'))

        # کامپایل مدل
        elastic_model.compile(optimizer='rmsprop',
                             loss='categorical_crossentropy',
                             metrics=['accuracy'])

        # آموزش مدل
        history = elastic_model.fit(partial_x_train, partial_y_train,
                                   epochs=20, batch_size=512,
                                   validation_data=(x_val, y_val),
                                   verbose=1)
        
        # ذخیره تاریخچه
        histories[combo_key] = history.history
        
        # ذخیره بهترین دقت اعتبارسنجی
        best_val_accuracies[combo_key] = max(history.history['val_accuracy'])

# پیدا کردن بهترین ترکیب
best_combo = max(best_val_accuracies, key=best_val_accuracies.get)
print(f"\nBest combination: {best_combo} with validation accuracy: {best_val_accuracies[best_combo]:.4f}")

for combo_key in histories:
    history = histories[combo_key]
    
    # استخراج مقادیر
    train_acc = history['accuracy']
    val_acc = history['val_accuracy']
    train_loss = history['loss']
    val_loss = history['val_loss']
    
    # چاپ مقادیر برای هر epoch
    print(f"\nResults for {combo_key}:")
    print("Epoch | Train Acc | Val Acc | Train Loss | Val Loss")
    print("-" * 50)
    for epoch in range(len(train_acc)):
        print(f"{epoch+1:5d} | {train_acc[epoch]:.4f}   | {val_acc[epoch]:.4f} | {train_loss[epoch]:.4f}    | {val_loss[epoch]:.4f}")
        
# رسم نمودارهای جداگانه برای هر ترکیب
for combo_key in histories:
    history = histories[combo_key]
    
    plt.figure(figsize=(12, 4))
    
    # نمودار دقت
    plt.subplot(1, 2, 1)
    plt.plot(history['accuracy'], label='Train Accuracy')
    plt.plot(history['val_accuracy'], '--', label='Validation Accuracy')
    plt.title(f'Accuracy ({combo_key})')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)
    
    # نمودار خطا
    plt.subplot(1, 2, 2)
    plt.plot(history['loss'], label='Train Loss')
    plt.plot(history['val_loss'], '--', label='Validation Loss')
    plt.title(f'Loss ({combo_key})')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    
    plt.tight_layout()
    plt.show()

# رسم نمودار مقایسه‌ای برای همه ترکیب‌ها
plt.figure(figsize=(12, 8))

# نمودار دقت اعتبارسنجی
plt.subplot(2, 1, 1)
for combo_key in histories:
    plt.plot(histories[combo_key]['val_accuracy'], label=combo_key)
plt.title('Validation Accuracy Comparison for Different L1 and L2 Combinations')
plt.xlabel('Epoch')
plt.ylabel('Validation Accuracy')
plt.legend()
plt.grid(True)

# نمودار خطای اعتبارسنجی
plt.subplot(2, 1, 2)
for combo_key in histories:
    plt.plot(histories[combo_key]['val_loss'], label=combo_key)
plt.title('Validation Loss Comparison for Different L1 and L2 Combinations')
plt.xlabel('Epoch')
plt.ylabel('Validation Loss')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

Training model with L1=0.0001, L2=0.0001
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.3331 - loss: 4.0175 - val_accuracy: 0.6360 - val_loss: 2.4865
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6637 - loss: 2.2589 - val_accuracy: 0.6790 - val_loss: 1.8980
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7248 - loss: 1.7128 - val_accuracy: 0.7330 - val_loss: 1.6041
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7702 - loss: 1.4267 - val_accuracy: 0.7550 - val_loss: 1.4478
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7938 - loss: 1.2773 - val_accuracy: 0.7700 - val_loss: 1.3450
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8138 - loss: 1.1379 - val_accuracy: 0.7890 - val_loss: 1.3059
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8353 - loss: 1.0551 - val_accuracy: 0.7860 - val_loss: 1.2879
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8454 - loss: 1.0114 - val_accuracy: 0.8070 - val_loss: 1.2277
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8587 - loss: 0.9441 - val_accuracy: 0.8120 - val_loss: 1.1971
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8735 - loss: 0.8931 - val_accuracy: 0.7980 - val_loss: 1.2182
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8841 - loss: 0.8431 - val_accuracy: 0.8100 - val_loss: 1.1919
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8951 - loss: 0.7983 - val_accuracy: 0.8050 - val_loss: 1.2064
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9043 - loss: 0.7689 - val_accuracy: 0.8160 - val_loss: 1.1860
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8992 - loss: 0.7581 - val_accuracy: 0.8220 - val_loss: 1.1582
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9175 - loss: 0.7046 - val_accuracy: 0.8210 - val_loss: 1.1640
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9205 - loss: 0.6928 - val_accuracy: 0.8130 - val_loss: 1.1799
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9244 - loss: 0.6654 - val_accuracy: 0.8100 - val_loss: 1.1829
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9296 - loss: 0.6500 - val_accuracy: 0.8220 - val_loss: 1.1585
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9245 - loss: 0.6446 - val_accuracy: 0.8270 - val_loss: 1.1541
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9326 - loss: 0.6207 - val_accuracy: 0.8110 - val_loss: 1.1996

Training model with L1=0.0001, L2=0.001
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.3667 - loss: 4.2529 - val_accuracy: 0.6400 - val_loss: 2.6601
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6681 - loss: 2.3772 - val_accuracy: 0.6890 - val_loss: 1.9694
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7177 - loss: 1.7885 - val_accuracy: 0.7250 - val_loss: 1.6725
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7507 - loss: 1.5337 - val_accuracy: 0.7390 - val_loss: 1.5301
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7800 - loss: 1.3590 - val_accuracy: 0.7610 - val_loss: 1.4510
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7941 - loss: 1.2907 - val_accuracy: 0.7610 - val_loss: 1.4107
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8198 - loss: 1.1930 - val_accuracy: 0.7850 - val_loss: 1.3666
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8259 - loss: 1.1370 - val_accuracy: 0.7890 - val_loss: 1.3405
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8454 - loss: 1.0737 - val_accuracy: 0.7890 - val_loss: 1.3189
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8419 - loss: 1.0498 - val_accuracy: 0.7880 - val_loss: 1.3116
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8610 - loss: 1.0062 - val_accuracy: 0.8000 - val_loss: 1.2810
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8660 - loss: 0.9811 - val_accuracy: 0.8070 - val_loss: 1.2763
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8737 - loss: 0.9533 - val_accuracy: 0.8010 - val_loss: 1.2621
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8842 - loss: 0.9213 - val_accuracy: 0.8040 - val_loss: 1.2684
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8873 - loss: 0.9100 - val_accuracy: 0.8090 - val_loss: 1.2732
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8980 - loss: 0.8625 - val_accuracy: 0.7770 - val_loss: 1.3269
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8933 - loss: 0.8755 - val_accuracy: 0.8050 - val_loss: 1.2458
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9016 - loss: 0.8494 - val_accuracy: 0.8000 - val_loss: 1.2762
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9149 - loss: 0.8148 - val_accuracy: 0.8020 - val_loss: 1.2813
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9152 - loss: 0.8049 - val_accuracy: 0.8130 - val_loss: 1.2494

Training model with L1=0.0001, L2=0.01
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.3973 - loss: 5.3811 - val_accuracy: 0.5910 - val_loss: 3.1004
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6199 - loss: 2.8233 - val_accuracy: 0.6620 - val_loss: 2.3427
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6797 - loss: 2.2558 - val_accuracy: 0.6910 - val_loss: 2.1198
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6972 - loss: 2.0739 - val_accuracy: 0.7040 - val_loss: 1.9951
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7207 - loss: 1.9365 - val_accuracy: 0.7020 - val_loss: 1.9196
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7277 - loss: 1.8582 - val_accuracy: 0.7180 - val_loss: 1.8467
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7332 - loss: 1.7780 - val_accuracy: 0.7240 - val_loss: 1.7859
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7385 - loss: 1.7430 - val_accuracy: 0.7220 - val_loss: 1.7554
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7475 - loss: 1.6758 - val_accuracy: 0.7330 - val_loss: 1.7151
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7501 - loss: 1.6596 - val_accuracy: 0.7320 - val_loss: 1.6936
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7619 - loss: 1.5963 - val_accuracy: 0.7280 - val_loss: 1.6835
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7584 - loss: 1.5864 - val_accuracy: 0.7300 - val_loss: 1.6401
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7718 - loss: 1.5466 - val_accuracy: 0.7390 - val_loss: 1.6262
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7704 - loss: 1.5279 - val_accuracy: 0.7540 - val_loss: 1.6083
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7797 - loss: 1.4971 - val_accuracy: 0.7510 - val_loss: 1.5907
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7843 - loss: 1.4749 - val_accuracy: 0.7470 - val_loss: 1.5822
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7803 - loss: 1.4734 - val_accuracy: 0.7550 - val_loss: 1.5721
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7877 - loss: 1.4372 - val_accuracy: 0.7420 - val_loss: 1.5906
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7888 - loss: 1.4276 - val_accuracy: 0.7610 - val_loss: 1.5457
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7975 - loss: 1.3990 - val_accuracy: 0.7590 - val_loss: 1.5327

Training model with L1=0.001, L2=0.0001
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.3006 - loss: 8.6082 - val_accuracy: 0.5780 - val_loss: 3.2660
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5922 - loss: 3.0204 - val_accuracy: 0.5960 - val_loss: 2.6550
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6426 - loss: 2.6047 - val_accuracy: 0.6480 - val_loss: 2.4651
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6722 - loss: 2.4371 - val_accuracy: 0.6840 - val_loss: 2.3503
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6871 - loss: 2.3187 - val_accuracy: 0.6880 - val_loss: 2.2588
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6934 - loss: 2.2166 - val_accuracy: 0.6900 - val_loss: 2.1798
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6990 - loss: 2.1677 - val_accuracy: 0.6940 - val_loss: 2.1245
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7104 - loss: 2.0777 - val_accuracy: 0.7040 - val_loss: 2.1103
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7174 - loss: 2.0409 - val_accuracy: 0.7000 - val_loss: 2.0507
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7216 - loss: 1.9905 - val_accuracy: 0.7060 - val_loss: 2.0103
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7223 - loss: 1.9814 - val_accuracy: 0.7090 - val_loss: 1.9682
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7231 - loss: 1.9458 - val_accuracy: 0.7100 - val_loss: 1.9466
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7265 - loss: 1.9376 - val_accuracy: 0.7270 - val_loss: 1.9330
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7318 - loss: 1.8960 - val_accuracy: 0.7180 - val_loss: 1.9226
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7351 - loss: 1.8678 - val_accuracy: 0.7260 - val_loss: 1.9071
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7302 - loss: 1.8751 - val_accuracy: 0.7290 - val_loss: 1.8699
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7494 - loss: 1.8242 - val_accuracy: 0.7380 - val_loss: 1.8817
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7544 - loss: 1.8129 - val_accuracy: 0.7260 - val_loss: 1.8549
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7517 - loss: 1.8226 - val_accuracy: 0.7360 - val_loss: 1.8674
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7587 - loss: 1.7915 - val_accuracy: 0.7520 - val_loss: 1.8230

Training model with L1=0.001, L2=0.001
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.3348 - loss: 8.7108 - val_accuracy: 0.5430 - val_loss: 3.2696
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5742 - loss: 3.0561 - val_accuracy: 0.6180 - val_loss: 2.6998
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6285 - loss: 2.6554 - val_accuracy: 0.6560 - val_loss: 2.5053
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6592 - loss: 2.4916 - val_accuracy: 0.6670 - val_loss: 2.4011
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6833 - loss: 2.3615 - val_accuracy: 0.6880 - val_loss: 2.2972
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6938 - loss: 2.2776 - val_accuracy: 0.6870 - val_loss: 2.2266
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7047 - loss: 2.1856 - val_accuracy: 0.6890 - val_loss: 2.1872
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7086 - loss: 2.1480 - val_accuracy: 0.6960 - val_loss: 2.1405
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7122 - loss: 2.0844 - val_accuracy: 0.7010 - val_loss: 2.0927
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7094 - loss: 2.0756 - val_accuracy: 0.7050 - val_loss: 2.0603
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7104 - loss: 2.0524 - val_accuracy: 0.7040 - val_loss: 2.0394
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7186 - loss: 2.0076 - val_accuracy: 0.7100 - val_loss: 2.0090
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7319 - loss: 1.9546 - val_accuracy: 0.7160 - val_loss: 1.9851
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7260 - loss: 1.9665 - val_accuracy: 0.7130 - val_loss: 1.9583
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7331 - loss: 1.9219 - val_accuracy: 0.7170 - val_loss: 1.9572
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7356 - loss: 1.9359 - val_accuracy: 0.7080 - val_loss: 1.9365
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7356 - loss: 1.8975 - val_accuracy: 0.7200 - val_loss: 1.9242
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7364 - loss: 1.8988 - val_accuracy: 0.7200 - val_loss: 1.9135
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7505 - loss: 1.8709 - val_accuracy: 0.7390 - val_loss: 1.9021
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7534 - loss: 1.8329 - val_accuracy: 0.7330 - val_loss: 1.8982

Training model with L1=0.001, L2=0.01
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.3394 - loss: 9.7393 - val_accuracy: 0.5270 - val_loss: 3.8791
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5335 - loss: 3.6284 - val_accuracy: 0.5660 - val_loss: 3.2119
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5677 - loss: 3.1539 - val_accuracy: 0.5930 - val_loss: 2.9388
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5965 - loss: 2.9293 - val_accuracy: 0.6270 - val_loss: 2.7728
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6331 - loss: 2.7633 - val_accuracy: 0.6610 - val_loss: 2.6294
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6638 - loss: 2.6079 - val_accuracy: 0.6660 - val_loss: 2.5298
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6667 - loss: 2.5324 - val_accuracy: 0.6780 - val_loss: 2.4346
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6750 - loss: 2.4274 - val_accuracy: 0.6860 - val_loss: 2.3695
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6791 - loss: 2.3656 - val_accuracy: 0.6640 - val_loss: 2.3241
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6912 - loss: 2.2885 - val_accuracy: 0.6760 - val_loss: 2.3017
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6913 - loss: 2.2457 - val_accuracy: 0.6920 - val_loss: 2.2222
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6996 - loss: 2.1920 - val_accuracy: 0.6910 - val_loss: 2.1653
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6988 - loss: 2.1486 - val_accuracy: 0.6860 - val_loss: 2.1425
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6958 - loss: 2.1387 - val_accuracy: 0.6930 - val_loss: 2.1193
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6959 - loss: 2.1215 - val_accuracy: 0.6920 - val_loss: 2.0916
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7015 - loss: 2.0859 - val_accuracy: 0.6950 - val_loss: 2.0841
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7034 - loss: 2.0574 - val_accuracy: 0.6920 - val_loss: 2.0590
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6946 - loss: 2.0756 - val_accuracy: 0.6990 - val_loss: 2.0417
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7077 - loss: 2.0131 - val_accuracy: 0.6970 - val_loss: 2.0468
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7034 - loss: 2.0257 - val_accuracy: 0.6930 - val_loss: 2.0145

Training model with L1=0.01, L2=0.0001
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.2311 - loss: 50.2633 - val_accuracy: 0.3540 - val_loss: 10.3156
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3593 - loss: 9.9620 - val_accuracy: 0.3850 - val_loss: 8.9585
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4242 - loss: 8.8240 - val_accuracy: 0.5030 - val_loss: 8.2097
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5019 - loss: 8.1258 - val_accuracy: 0.5070 - val_loss: 7.6450
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5099 - loss: 7.5596 - val_accuracy: 0.4970 - val_loss: 7.1819
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5022 - loss: 7.1305 - val_accuracy: 0.5090 - val_loss: 6.7817
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5002 - loss: 6.7592 - val_accuracy: 0.5070 - val_loss: 6.4439
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5046 - loss: 6.4203 - val_accuracy: 0.5120 - val_loss: 6.1626
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5098 - loss: 6.1489 - val_accuracy: 0.5090 - val_loss: 5.9287
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5113 - loss: 5.9293 - val_accuracy: 0.5220 - val_loss: 5.7452
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5135 - loss: 5.7440 - val_accuracy: 0.5230 - val_loss: 5.5949
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5130 - loss: 5.6153 - val_accuracy: 0.5200 - val_loss: 5.4929
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5184 - loss: 5.5264 - val_accuracy: 0.5200 - val_loss: 5.4219
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5162 - loss: 5.4693 - val_accuracy: 0.5200 - val_loss: 5.3807
Epoch 15/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5162 - loss: 5.4325 - val_accuracy: 0.5200 - val_loss: 5.3446
Epoch 16/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5227 - loss: 5.3934 - val_accuracy: 0.5300 - val_loss: 5.3102
Epoch 17/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5307 - loss: 5.3365 - val_accuracy: 0.5350 - val_loss: 5.2795
Epoch 18/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5325 - loss: 5.3276 - val_accuracy: 0.5310 - val_loss: 5.2552
Epoch 19/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5379 - loss: 5.2897 - val_accuracy: 0.5390 - val_loss: 5.2236
Epoch 20/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5474 - loss: 5.2456 - val_accuracy: 0.5460 - val_loss: 5.1995

Training model with L1=0.01, L2=0.001
Epoch 1/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.2434 - loss: 50.4409 - val_accuracy: 0.3950 - val_loss: 10.2265
Epoch 2/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3945 - loss: 9.9019 - val_accuracy: 0.4990 - val_loss: 8.9461
Epoch 3/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4874 - loss: 8.8264 - val_accuracy: 0.5080 - val_loss: 8.2305
Epoch 4/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5058 - loss: 8.1480 - val_accuracy: 0.5120 - val_loss: 7.6744
Epoch 5/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5067 - loss: 7.6141 - val_accuracy: 0.5100 - val_loss: 7.2037
Epoch 6/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5012 - loss: 7.1705 - val_accuracy: 0.5240 - val_loss: 6.7977
Epoch 7/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5161 - loss: 6.7497 - val_accuracy: 0.5130 - val_loss: 6.4580
Epoch 8/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5115 - loss: 6.4303 - val_accuracy: 0.5170 - val_loss: 6.1634
Epoch 9/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5092 - loss: 6.1552 - val_accuracy: 0.5140 - val_loss: 5.9214
Epoch 10/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5144 - loss: 5.9169 - val_accuracy: 0.5260 - val_loss: 5.7237
Epoch 11/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5172 - loss: 5.7388 - val_accuracy: 0.5240 - val_loss: 5.5753
Epoch 12/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5092 - loss: 5.6197 - val_accuracy: 0.5210 - val_loss: 5.4707
Epoch 13/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5142 - loss: 5.5156 - val_accuracy: 0.5280 - val_loss: 5.4147
Epoch 14/20
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5313 - loss: 5.4288 - val_accuracy: 0.5290 - val_loss: 5.3759
Epoch 15/20

L1 Regularization

In [21]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import models, layers, regularizers

# فرض: partial_x_train, partial_y_train, x_val, y_val قبلاً آماده شده‌اند

l1_values = [0.0001, 0.001, 0.01]
histories = {}

for l1_value in l1_values:
    print(f"\nTraining model with L1 = {l1_value}")
    model = models.Sequential()
    model.add(layers.Dense(64, activation='relu',
                           kernel_regularizer=regularizers.l1(l1_value),
                           input_shape=(10000,)))
    model.add(layers.Dense(64, activation='relu',
                           kernel_regularizer=regularizers.l1(l1_value)))
    model.add(layers.Dense(46, activation='softmax'))

    model.compile(optimizer='rmsprop',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    history = model.fit(partial_x_train, partial_y_train,
                        epochs=20, batch_size=512,
                        validation_data=(x_val, y_val),
                        verbose=0)
    
    histories[l1_value] = history


# رسم نمودار جداگانه برای هر مقدار L1
epochs = range(1, 21)

for l1_value, history in histories.items():
    plt.figure(figsize=(14, 5))
    plt.suptitle(f"L1 Regularization = {l1_value}", fontsize=14)

    # دقت (Accuracy)
    plt.subplot(1, 2, 1)
    plt.plot(epochs, history.history['accuracy'], 'bo--', label='Train Acc')
    plt.plot(epochs, history.history['val_accuracy'], 'r^-', label='Val Acc')
    plt.title('Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()

    # خطا (Loss)
    plt.subplot(1, 2, 2)
    plt.plot(epochs, history.history['loss'], 'bo--', label='Train Loss')
    plt.plot(epochs, history.history['val_loss'], 'r^-', label='Val Loss')
    plt.title('Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    plt.tight_layout(rect=[0, 0, 1, 0.95])
    plt.show()

    # چاپ مقادیر فقط مربوط به آخرین ایپاک (Epoch 20)
    last_epoch = 19  # چون ایپاک‌ها از 0 شروع می‌شوند
    print(f"\nL1 = {l1_value}")
    print("Epoch\tTrain Acc\tVal Acc\t\tTrain Loss\tVal Loss")
    print(f"20\t{history.history['accuracy'][last_epoch]:.4f}\t\t"
          f"{history.history['val_accuracy'][last_epoch]:.4f}\t\t"
          f"{history.history['loss'][last_epoch]:.4f}\t\t{history.history['val_loss'][last_epoch]:.4f}")

Training model with L1 = 0.0001

Training model with L1 = 0.001

Training model with L1 = 0.01

L1 = 0.0001
Epoch	Train Acc	Val Acc		Train Loss	Val Loss
20	0.9312		0.8100		0.6179		1.1867

L1 = 0.001
Epoch	Train Acc	Val Acc		Train Loss	Val Loss
20	0.7667		0.7570		1.7959		1.8204

L1 = 0.01
Epoch	Train Acc	Val Acc		Train Loss	Val Loss
20	0.5588		0.5770		5.0314		4.9761

In [24]:
# رسم نمودارهای جداگانه برای هر ترکیب
for combo_key in histories:
    history = histories[combo_key]
    
    plt.figure(figsize=(12, 4))
    
    # نمودار دقت
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy', color='blue')
    plt.plot(history.history['val_accuracy'], '--', label='Validation Accuracy', color='red')
    plt.title(f'Accuracy ({combo_key})')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)
    
    # نمودار خطا
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss', color='blue')
    plt.plot(history.history['val_loss'], '--', label='Validation Loss', color='red')
    plt.title(f'Loss ({combo_key})')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    
    plt.tight_layout()
    plt.show()

# # رسم نمودار مقایسه‌ای برای همه ترکیب‌ها
# plt.figure(figsize=(12, 8))

# # نمودار دقت اعتبارسنجی
# plt.subplot(2, 1, 1)
# for combo_key in histories:
#     plt.plot(histories[combo_key].history['val_accuracy'], label=combo_key)
# plt.title('Validation Accuracy Comparison for Different L1 and L2 Combinations')
# plt.xlabel('Epoch')
# plt.ylabel('Validation Accuracy')
# plt.legend(loc='best')
# plt.grid(True)

# # نمودار خطای اعتبارسنجی
# plt.subplot(2, 1, 2)
# for combo_key in histories:
#     plt.plot(histories[combo_key].history['val_loss'], label=combo_key)
# plt.title('Validation Loss Comparison for Different L1 and L2 Combinations')
# plt.xlabel('Epoch')
# plt.ylabel('Validation Loss')
# plt.legend(loc='best')
# plt.grid(True)

# plt.tight_layout()
# plt.show()

Dropout

In [25]:
import matplotlib.pyplot as plt
from tensorflow.keras import models, layers
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import reuters
import numpy as np

# بارگذاری داده‌ها
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=10000)

# تبدیل به one-hot
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.0
    return results

x_train = vectorize_sequences(x_train)
x_test = vectorize_sequences(x_test)

one_hot_train_labels = to_categorical(y_train)
one_hot_test_labels = to_categorical(y_test)

# تقسیم داده‌های آموزش به train و validation
x_val = x_train[:1000]
partial_x_train = x_train[1000:]

y_val = one_hot_train_labels[:1000]
partial_y_train = one_hot_train_labels[1000:]

# تابع برای آموزش و رسم نمودار
def train_and_plot(dropout_rates, neurons, epochs):
    history_dict = {}
    
    # ساخت مدل
    def build_model(dropout_rate):
        model = models.Sequential()
        model.add(layers.Dense(neurons, activation='relu', input_shape=(10000,)))
        model.add(layers.Dropout(dropout_rate))
        model.add(layers.Dense(neurons, activation='relu'))
        model.add(layers.Dropout(dropout_rate))
        model.add(layers.Dense(46, activation='softmax'))
        model.compile(optimizer='rmsprop',
                      loss='categorical_crossentropy',
                      metrics=['accuracy'])
        return model
    
    # آموزش مدل‌ها
    for rate in dropout_rates:
        print(f"\nTraining with dropout rate = {rate}, neurons = {neurons}")
        model = build_model(rate)
        history = model.fit(
            partial_x_train, partial_y_train,
            epochs=epochs,
            batch_size=512,
            validation_data=(x_val, y_val),
            verbose=0
        )
        history_dict[rate] = history
    
    # رسم نمودارهای جداگانه برای هر نرخ Dropout
    for rate in dropout_rates:
        history = history_dict[rate].history
        
        # چاپ مقادیر برای هر epoch
        print(f"\nResults for Dropout Rate = {rate}:")
        print("Epoch | Train Acc | Val Acc | Train Loss | Val Loss")
        print("-" * 50)
        for epoch in range(len(history['accuracy'])):
            print(f"{epoch+1:5d} | {history['accuracy'][epoch]:.4f}   | {history['val_accuracy'][epoch]:.4f} | {history['loss'][epoch]:.4f}    | {history['val_loss'][epoch]:.4f}")
        
        # رسم نمودارهای جداگانه
        plt.figure(figsize=(12, 4))
        
        # نمودار دقت
        plt.subplot(1, 2, 1)
        plt.plot(history['accuracy'], label='Train Accuracy', color='blue')
        plt.plot(history['val_accuracy'], '--', label='Validation Accuracy', color='red')
        plt.title(f'Accuracy (Dropout={rate})')
        plt.xlabel('Epoch')
        plt.ylabel('Accuracy')
        plt.legend()
        plt.grid(True)
        
        # نمودار خطا
        plt.subplot(1, 2, 2)
        plt.plot(history['loss'], label='Train Loss', color='blue')
        plt.plot(history['val_loss'], '--', label='Validation Loss', color='red')
        plt.title(f'Loss (Dropout={rate})')
        plt.xlabel('Epoch')
        plt.ylabel('Loss')
        plt.legend()
        plt.grid(True)
        
        plt.tight_layout()
        plt.show()
    
    # رسم نمودار مقایسه‌ای برای همه نرخ‌های Dropout
    plt.figure(figsize=(12, 8))
    
    # نمودار دقت اعتبارسنجی
    plt.subplot(2, 1, 1)
    for rate in dropout_rates:
        plt.plot(history_dict[rate].history['val_accuracy'], label=f'Dropout={rate}')
    plt.title(f'Validation Accuracy Comparison (Neurons={neurons})')
    plt.xlabel('Epoch')
    plt.ylabel('Validation Accuracy')
    plt.legend(loc='best')
    plt.grid(True)
    
    # نمودار خطای اعتبارسنجی
    plt.subplot(2, 1, 2)
    for rate in dropout_rates:
        plt.plot(history_dict[rate].history['val_loss'], label=f'Dropout={rate}')
    plt.title(f'Validation Loss Comparison (Neurons={neurons})')
    plt.xlabel('Epoch')
    plt.ylabel('Validation Loss')
    plt.legend(loc='best')
    plt.grid(True)
    
    plt.tight_layout()
    plt.show()

# اجرای آموزش برای مدل با 64 نورون (20 epoch)
print("Training Model with 64 Neurons")
train_and_plot(dropout_rates=[0.3, 0.5, 0.7], neurons=64, epochs=20)

# اجرای آموزش برای مدل با 128 نورون (30 epoch)
print("\nTraining Model with 128 Neurons")
train_and_plot(dropout_rates=[0.3, 0.5, 0.7], neurons=128, epochs=30)

Training Model with 64 Neurons

Training with dropout rate = 0.3, neurons = 64

Training with dropout rate = 0.5, neurons = 64

Training with dropout rate = 0.7, neurons = 64

Results for Dropout Rate = 0.3:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4519   | 0.6030 | 2.7184    | 1.7797
    2 | 0.6077   | 0.6590 | 1.7233    | 1.4351
    3 | 0.6734   | 0.7140 | 1.4196    | 1.2777
    4 | 0.7108   | 0.7290 | 1.2460    | 1.1741
    5 | 0.7387   | 0.7600 | 1.1068    | 1.1056
    6 | 0.7656   | 0.7680 | 1.0007    | 1.0427
    7 | 0.7885   | 0.7710 | 0.9021    | 1.0139
    8 | 0.8048   | 0.7800 | 0.8232    | 0.9803
    9 | 0.8182   | 0.7870 | 0.7568    | 0.9509
   10 | 0.8339   | 0.8030 | 0.6986    | 0.9280
   11 | 0.8480   | 0.7990 | 0.6355    | 0.9258
   12 | 0.8589   | 0.8070 | 0.5827    | 0.9162
   13 | 0.8633   | 0.8140 | 0.5502    | 0.8894
   14 | 0.8758   | 0.8080 | 0.5026    | 0.9088
   15 | 0.8846   | 0.8080 | 0.4680    | 0.9107
   16 | 0.8921   | 0.8120 | 0.4320    | 0.9032
   17 | 0.8980   | 0.8120 | 0.4077    | 0.9144
   18 | 0.9040   | 0.8200 | 0.3796    | 0.8990
   19 | 0.9097   | 0.8170 | 0.3636    | 0.9213
   20 | 0.9133   | 0.8060 | 0.3398    | 0.9597

Results for Dropout Rate = 0.5:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.3321   | 0.5360 | 3.1615    | 2.1764
    2 | 0.5194   | 0.5950 | 2.1395    | 1.6571
    3 | 0.5784   | 0.6560 | 1.7738    | 1.4747
    4 | 0.6190   | 0.6800 | 1.5933    | 1.3716
    5 | 0.6518   | 0.6980 | 1.4552    | 1.2832
    6 | 0.6765   | 0.7120 | 1.3487    | 1.2337
    7 | 0.6949   | 0.7220 | 1.2574    | 1.1793
    8 | 0.7056   | 0.7310 | 1.1985    | 1.1449
    9 | 0.7229   | 0.7390 | 1.1443    | 1.1203
   10 | 0.7301   | 0.7480 | 1.0776    | 1.0904
   11 | 0.7434   | 0.7580 | 1.0225    | 1.0739
   12 | 0.7537   | 0.7680 | 0.9823    | 1.0543
   13 | 0.7641   | 0.7740 | 0.9331    | 1.0329
   14 | 0.7724   | 0.7830 | 0.8975    | 1.0118
   15 | 0.7830   | 0.7820 | 0.8549    | 1.0138
   16 | 0.7952   | 0.7890 | 0.8073    | 1.0096
   17 | 0.7965   | 0.7900 | 0.7956    | 0.9960
   18 | 0.8109   | 0.7890 | 0.7410    | 1.0107
   19 | 0.8140   | 0.7970 | 0.7317    | 0.9931
   20 | 0.8176   | 0.7930 | 0.6942    | 0.9927

Results for Dropout Rate = 0.7:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.2326   | 0.4390 | 3.3269    | 2.4975
    2 | 0.3899   | 0.5440 | 2.5646    | 1.9465
    3 | 0.4483   | 0.6020 | 2.2506    | 1.7673
    4 | 0.4975   | 0.6540 | 2.0186    | 1.6296
    5 | 0.5223   | 0.6580 | 1.8836    | 1.5495
    6 | 0.5526   | 0.6720 | 1.7927    | 1.4626
    7 | 0.5750   | 0.6880 | 1.7075    | 1.4160
    8 | 0.5965   | 0.6930 | 1.6258    | 1.3852
    9 | 0.6025   | 0.7030 | 1.5963    | 1.3483
   10 | 0.6195   | 0.7030 | 1.5255    | 1.3229
   11 | 0.6309   | 0.7050 | 1.4860    | 1.3049
   12 | 0.6392   | 0.7050 | 1.4406    | 1.2785
   13 | 0.6455   | 0.7070 | 1.4115    | 1.2689
   14 | 0.6587   | 0.7080 | 1.3750    | 1.2540
   15 | 0.6612   | 0.7110 | 1.3189    | 1.2383
   16 | 0.6604   | 0.7160 | 1.3111    | 1.2388
   17 | 0.6778   | 0.7200 | 1.2865    | 1.2324
   18 | 0.6773   | 0.7210 | 1.2786    | 1.2333
   19 | 0.6843   | 0.7200 | 1.2269    | 1.2262
   20 | 0.6859   | 0.7230 | 1.2224    | 1.2312

Training Model with 128 Neurons

Training with dropout rate = 0.3, neurons = 128

Training with dropout rate = 0.5, neurons = 128

Training with dropout rate = 0.7, neurons = 128

Results for Dropout Rate = 0.3:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4544   | 0.6360 | 2.5045    | 1.5771
    2 | 0.6703   | 0.7190 | 1.4713    | 1.2616
    3 | 0.7338   | 0.7510 | 1.1829    | 1.1306
    4 | 0.7796   | 0.7780 | 0.9871    | 1.0457
    5 | 0.8074   | 0.8020 | 0.8428    | 0.9689
    6 | 0.8349   | 0.8110 | 0.7220    | 0.9273
    7 | 0.8596   | 0.8140 | 0.6146    | 0.8975
    8 | 0.8794   | 0.8030 | 0.5322    | 0.9035
    9 | 0.8954   | 0.8120 | 0.4592    | 0.8911
   10 | 0.9058   | 0.8200 | 0.4050    | 0.8746
   11 | 0.9172   | 0.8190 | 0.3600    | 0.8713
   12 | 0.9261   | 0.8220 | 0.3115    | 0.8723
   13 | 0.9323   | 0.8150 | 0.2780    | 0.9095
   14 | 0.9354   | 0.8250 | 0.2646    | 0.9278
   15 | 0.9416   | 0.8140 | 0.2358    | 0.9310
   16 | 0.9460   | 0.8210 | 0.2172    | 0.9251
   17 | 0.9473   | 0.8230 | 0.2080    | 0.9410
   18 | 0.9500   | 0.8160 | 0.1945    | 0.9480
   19 | 0.9498   | 0.8200 | 0.1812    | 0.9406
   20 | 0.9543   | 0.8180 | 0.1671    | 0.9833
   21 | 0.9543   | 0.8200 | 0.1629    | 0.9771
   22 | 0.9539   | 0.8190 | 0.1622    | 0.9729
   23 | 0.9572   | 0.8140 | 0.1513    | 1.0112
   24 | 0.9579   | 0.8160 | 0.1457    | 1.0054
   25 | 0.9564   | 0.8130 | 0.1429    | 0.9961
   26 | 0.9582   | 0.8220 | 0.1385    | 1.0206
   27 | 0.9579   | 0.8120 | 0.1330    | 1.0346
   28 | 0.9612   | 0.8120 | 0.1275    | 1.0288
   29 | 0.9589   | 0.8160 | 0.1270    | 1.0201
   30 | 0.9589   | 0.8170 | 0.1280    | 1.0026

Results for Dropout Rate = 0.5:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4441   | 0.5880 | 2.5792    | 1.6693
    2 | 0.6086   | 0.6850 | 1.6613    | 1.3838
    3 | 0.6792   | 0.7220 | 1.3855    | 1.2332
    4 | 0.7207   | 0.7370 | 1.2052    | 1.1404
    5 | 0.7444   | 0.7590 | 1.0885    | 1.0772
    6 | 0.7749   | 0.7670 | 0.9594    | 1.0379
    7 | 0.7973   | 0.7840 | 0.8633    | 0.9863
    8 | 0.8089   | 0.8020 | 0.8042    | 0.9582
    9 | 0.8265   | 0.8050 | 0.7253    | 0.9390
   10 | 0.8395   | 0.8100 | 0.6596    | 0.9251
   11 | 0.8519   | 0.8110 | 0.6189    | 0.9293
   12 | 0.8634   | 0.8050 | 0.5563    | 0.9407
   13 | 0.8733   | 0.8170 | 0.5134    | 0.9126
   14 | 0.8790   | 0.8170 | 0.4921    | 0.9153
   15 | 0.8849   | 0.8140 | 0.4585    | 0.9264
   16 | 0.8939   | 0.8120 | 0.4143    | 0.9547
   17 | 0.8988   | 0.8230 | 0.3943    | 0.9365
   18 | 0.9077   | 0.8220 | 0.3792    | 0.9449
   19 | 0.9080   | 0.8250 | 0.3469    | 0.9628
   20 | 0.9158   | 0.8260 | 0.3336    | 0.9539
   21 | 0.9191   | 0.8210 | 0.3186    | 0.9705
   22 | 0.9169   | 0.8300 | 0.3078    | 0.9453
   23 | 0.9257   | 0.8300 | 0.2849    | 0.9802
   24 | 0.9223   | 0.8180 | 0.2912    | 1.0023
   25 | 0.9336   | 0.8290 | 0.2604    | 1.0098
   26 | 0.9369   | 0.8260 | 0.2463    | 0.9993
   27 | 0.9344   | 0.8260 | 0.2517    | 1.0378
   28 | 0.9352   | 0.8270 | 0.2382    | 1.0507
   29 | 0.9385   | 0.8250 | 0.2255    | 1.0619
   30 | 0.9407   | 0.8260 | 0.2287    | 1.0348

Results for Dropout Rate = 0.7:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.2819   | 0.5410 | 3.1799    | 2.0705
    2 | 0.5050   | 0.6030 | 2.1309    | 1.6572
    3 | 0.5690   | 0.6530 | 1.8066    | 1.4973
    4 | 0.5998   | 0.6790 | 1.6571    | 1.4073
    5 | 0.6318   | 0.7020 | 1.5289    | 1.3203
    6 | 0.6538   | 0.7130 | 1.4363    | 1.2735
    7 | 0.6799   | 0.7170 | 1.3529    | 1.2372
    8 | 0.6893   | 0.7230 | 1.2893    | 1.1943
    9 | 0.7072   | 0.7310 | 1.2295    | 1.1787
   10 | 0.7132   | 0.7350 | 1.1704    | 1.1514
   11 | 0.7229   | 0.7530 | 1.1368    | 1.1228
   12 | 0.7316   | 0.7560 | 1.0876    | 1.1114
   13 | 0.7478   | 0.7570 | 1.0273    | 1.1041
   14 | 0.7543   | 0.7610 | 1.0116    | 1.0996
   15 | 0.7591   | 0.7720 | 0.9737    | 1.0872
   16 | 0.7651   | 0.7720 | 0.9470    | 1.0754
   17 | 0.7712   | 0.7760 | 0.9152    | 1.0638
   18 | 0.7791   | 0.7760 | 0.8830    | 1.0616
   19 | 0.7811   | 0.7810 | 0.8668    | 1.0612
   20 | 0.7863   | 0.7790 | 0.8411    | 1.0518
   21 | 0.7919   | 0.7800 | 0.8150    | 1.0589
   22 | 0.7948   | 0.7830 | 0.7983    | 1.0622
   23 | 0.7992   | 0.7940 | 0.7745    | 1.0553
   24 | 0.8064   | 0.7860 | 0.7468    | 1.0698
   25 | 0.8087   | 0.7930 | 0.7299    | 1.0696
   26 | 0.8141   | 0.7930 | 0.7107    | 1.0831
   27 | 0.8195   | 0.7930 | 0.7007    | 1.0939
   28 | 0.8177   | 0.8010 | 0.6860    | 1.0926
   29 | 0.8267   | 0.7980 | 0.6713    | 1.0940
   30 | 0.8244   | 0.8020 | 0.6641    | 1.0917

In [26]:
import matplotlib.pyplot as plt
from tensorflow.keras import models, layers
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import reuters
import numpy as np

# بارگذاری داده‌ها
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=10000)

# تبدیل به one-hot
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.0
    return results

x_train = vectorize_sequences(x_train)
x_test = vectorize_sequences(x_test)

one_hot_train_labels = to_categorical(y_train)
one_hot_test_labels = to_categorical(y_test)

# تقسیم داده‌های آموزش به train و validation
x_val = x_train[:1000]
partial_x_train = x_train[1000:]

y_val = one_hot_train_labels[:1000]
partial_y_train = one_hot_train_labels[1000:]

# تابع برای آموزش و رسم نمودار
def train_and_plot(dropout_rates, neurons, epochs):
    history_dict = {}
    # *** تغییر جدید: ذخیره بهترین مدل‌ها ***
    best_models = []  # لیست برای ذخیره اطلاعات بهترین مدل‌ها
    
    # ساخت مدل
    def build_model(dropout_rate):
        model = models.Sequential()
        model.add(layers.Dense(neurons, activation='relu', input_shape=(10000,)))
        model.add(layers.Dropout(dropout_rate))
        model.add(layers.Dense(neurons, activation='relu'))
        model.add(layers.Dropout(dropout_rate))
        model.add(layers.Dense(46, activation='softmax'))
        model.compile(optimizer='rmsprop',
                      loss='categorical_crossentropy',
                      metrics=['accuracy'])
        return model
    
    # آموزش مدل‌ها
    for rate in dropout_rates:
        print(f"\nTraining with dropout rate = {rate}, neurons = {neurons}")
        model = build_model(rate)
        history = model.fit(
            partial_x_train, partial_y_train,
            epochs=epochs,
            batch_size=512,
            validation_data=(x_val, y_val),
            verbose=0
        )
        history_dict[rate] = history
        
        # *** تغییر جدید: یافتن بهترین val_accuracy برای این نرخ Dropout ***
        history_data = history.history
        max_val_acc = max(history_data['val_accuracy'])
        max_val_acc_epoch = history_data['val_accuracy'].index(max_val_acc) + 1
        best_model_info = {
            'dropout_rate': rate,
            'neurons': neurons,
            'epoch': max_val_acc_epoch,
            'val_accuracy': max_val_acc,
            'val_loss': history_data['val_loss'][max_val_acc_epoch - 1],
            'train_accuracy': history_data['accuracy'][max_val_acc_epoch - 1],
            'train_loss': history_data['loss'][max_val_acc_epoch - 1]
        }
        best_models.append(best_model_info)
    
    # رسم نمودارهای جداگانه برای هر نرخ Dropout
    for rate in dropout_rates:
        history = history_dict[rate].history
        
        # چاپ مقادیر برای هر epoch
        print(f"\nResults for Dropout Rate = {rate}:")
        print("Epoch | Train Acc | Val Acc | Train Loss | Val Loss")
        print("-" * 50)
        for epoch in range(len(history['accuracy'])):
            print(f"{epoch+1:5d} | {history['accuracy'][epoch]:.4f}   | {history['val_accuracy'][epoch]:.4f} | {history['loss'][epoch]:.4f}    | {history['val_loss'][epoch]:.4f}")
        
        # رسم نمودارهای جداگانه
        plt.figure(figsize=(12, 4))
        
        # نمودار دقت
        plt.subplot(1, 2, 1)
        plt.plot(history['accuracy'], label='Train Accuracy', color='blue')
        plt.plot(history['val_accuracy'], '--', label='Validation Accuracy', color='red')
        plt.title(f'Accuracy (Dropout={rate})')
        plt.xlabel('Epoch')
        plt.ylabel('Accuracy')
        plt.legend()
        plt.grid(True)
        
        # نمودار خطا
        plt.subplot(1, 2, 2)
        plt.plot(history['loss'], label='Train Loss', color='blue')
        plt.plot(history['val_loss'], '--', label='Validation Loss', color='red')
        plt.title(f'Loss (Dropout={rate})')
        plt.xlabel('Epoch')
        plt.ylabel('Loss')
        plt.legend()
        plt.grid(True)
        
        plt.tight_layout()
        plt.show()
    
    # رسم نمودار مقایسه‌ای برای همه نرخ‌های Dropout
    plt.figure(figsize=(12, 8))
    
    # نمودار دقت اعتبارسنجی
    plt.subplot(2, 1, 1)
    for rate in dropout_rates:
        plt.plot(history_dict[rate].history['val_accuracy'], label=f'Dropout={rate}')
    plt.title(f'Validation Accuracy Comparison (Neurons={neurons})')
    plt.xlabel('Epoch')
    plt.ylabel('Validation Accuracy')
    plt.legend(loc='best')
    plt.grid(True)
    
    # نمودار خطای اعتبارسنجی
    plt.subplot(2, 1, 2)
    for rate in dropout_rates:
        plt.plot(history_dict[rate].history['val_loss'], label=f'Dropout={rate}')
    plt.title(f'Validation Loss Comparison (Neurons={neurons})')
    plt.xlabel('Epoch')
    plt.ylabel('Validation Loss')
    plt.legend(loc='best')
    plt.grid(True)
    
    plt.tight_layout()
    plt.show()
    
    # *** تغییر جدید: چاپ بهترین مدل‌ها برای این تعداد نورون ***
    print(f"\nBest Models for {neurons} Neurons:")
    print("Dropout | Epoch | Train Acc | Val Acc | Train Loss | Val Loss")
    print("-" * 60)
    for model_info in best_models:
        print(f"{model_info['dropout_rate']:.1f}     | {model_info['epoch']:5d} | {model_info['train_accuracy']:.4f}   | {model_info['val_accuracy']:.4f} | {model_info['train_loss']:.4f}    | {model_info['val_loss']:.4f}")

# اجرای آموزش برای مدل با 64 نورون (20 epoch)
print("Training Model with 64 Neurons")
train_and_plot(dropout_rates=[0.3, 0.5, 0.7], neurons=64, epochs=20)

# اجرای آموزش برای مدل با 128 نورون (30 epoch)
print("\nTraining Model with 128 Neurons")
train_and_plot(dropout_rates=[0.3, 0.5, 0.7], neurons=128, epochs=30)

Training Model with 64 Neurons

Training with dropout rate = 0.3, neurons = 64

Training with dropout rate = 0.5, neurons = 64

Training with dropout rate = 0.7, neurons = 64

Results for Dropout Rate = 0.3:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4405   | 0.6080 | 2.7894    | 1.8287
    2 | 0.6146   | 0.6690 | 1.7461    | 1.4220
    3 | 0.6792   | 0.7120 | 1.4269    | 1.2607
    4 | 0.7176   | 0.7310 | 1.2314    | 1.1653
    5 | 0.7417   | 0.7520 | 1.1111    | 1.0951
    6 | 0.7686   | 0.7640 | 1.0045    | 1.0441
    7 | 0.7851   | 0.7750 | 0.9089    | 0.9979
    8 | 0.8044   | 0.7870 | 0.8248    | 0.9770
    9 | 0.8172   | 0.7960 | 0.7652    | 0.9475
   10 | 0.8348   | 0.8100 | 0.6862    | 0.9156
   11 | 0.8448   | 0.8120 | 0.6472    | 0.9102
   12 | 0.8555   | 0.8110 | 0.5950    | 0.9048
   13 | 0.8663   | 0.8170 | 0.5481    | 0.8873
   14 | 0.8779   | 0.8180 | 0.5020    | 0.8915
   15 | 0.8834   | 0.8150 | 0.4744    | 0.8991
   16 | 0.8950   | 0.8210 | 0.4305    | 0.8950
   17 | 0.9007   | 0.8160 | 0.4096    | 0.8965
   18 | 0.9058   | 0.8170 | 0.3859    | 0.9106
   19 | 0.9112   | 0.8160 | 0.3632    | 0.9047
   20 | 0.9184   | 0.8190 | 0.3282    | 0.9277

Results for Dropout Rate = 0.5:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.3467   | 0.5140 | 3.0767    | 2.1540
    2 | 0.5061   | 0.6030 | 2.1246    | 1.6706
    3 | 0.5783   | 0.6650 | 1.7964    | 1.4936
    4 | 0.6250   | 0.6900 | 1.5944    | 1.3663
    5 | 0.6572   | 0.7080 | 1.4453    | 1.2744
    6 | 0.6824   | 0.7100 | 1.3499    | 1.2182
    7 | 0.6986   | 0.7180 | 1.2542    | 1.1630
    8 | 0.7124   | 0.7380 | 1.1951    | 1.1304
    9 | 0.7255   | 0.7490 | 1.1127    | 1.1028
   10 | 0.7392   | 0.7540 | 1.0580    | 1.0801
   11 | 0.7511   | 0.7680 | 1.0133    | 1.0493
   12 | 0.7637   | 0.7680 | 0.9688    | 1.0343
   13 | 0.7755   | 0.7740 | 0.9207    | 1.0127
   14 | 0.7816   | 0.7740 | 0.8771    | 1.0220
   15 | 0.7895   | 0.7820 | 0.8446    | 0.9996
   16 | 0.7962   | 0.7830 | 0.8122    | 1.0049
   17 | 0.8037   | 0.7870 | 0.7746    | 1.0027
   18 | 0.8077   | 0.7900 | 0.7629    | 0.9795
   19 | 0.8168   | 0.7890 | 0.7267    | 0.9965
   20 | 0.8207   | 0.7930 | 0.7076    | 0.9949

Results for Dropout Rate = 0.7:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.2042   | 0.5350 | 3.3940    | 2.5533
    2 | 0.3988   | 0.5770 | 2.5630    | 1.8783
    3 | 0.4713   | 0.5980 | 2.1933    | 1.6393
    4 | 0.5148   | 0.6240 | 1.9682    | 1.5546
    5 | 0.5470   | 0.6440 | 1.8355    | 1.4988
    6 | 0.5593   | 0.6780 | 1.7504    | 1.4678
    7 | 0.5799   | 0.6830 | 1.6705    | 1.4198
    8 | 0.5945   | 0.6960 | 1.5921    | 1.3886
    9 | 0.6031   | 0.7040 | 1.5611    | 1.3594
   10 | 0.6193   | 0.7040 | 1.5215    | 1.3379
   11 | 0.6289   | 0.7170 | 1.4727    | 1.3143
   12 | 0.6381   | 0.7150 | 1.4325    | 1.2933
   13 | 0.6416   | 0.7160 | 1.4075    | 1.2872
   14 | 0.6505   | 0.7160 | 1.3715    | 1.2702
   15 | 0.6671   | 0.7190 | 1.3243    | 1.2582
   16 | 0.6625   | 0.7230 | 1.3220    | 1.2536
   17 | 0.6729   | 0.7210 | 1.2790    | 1.2446
   18 | 0.6723   | 0.7220 | 1.2673    | 1.2362
   19 | 0.6850   | 0.7250 | 1.2358    | 1.2385
   20 | 0.6843   | 0.7230 | 1.2164    | 1.2306

Best Models for 64 Neurons:
Dropout | Epoch | Train Acc | Val Acc | Train Loss | Val Loss
------------------------------------------------------------
0.3     |    16 | 0.8950   | 0.8210 | 0.4305    | 0.8950
0.5     |    20 | 0.8207   | 0.7930 | 0.7076    | 0.9949
0.7     |    19 | 0.6850   | 0.7250 | 1.2358    | 1.2385

Training Model with 128 Neurons

Training with dropout rate = 0.3, neurons = 128

Training with dropout rate = 0.5, neurons = 128

Training with dropout rate = 0.7, neurons = 128

Results for Dropout Rate = 0.3:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4744   | 0.6300 | 2.5167    | 1.5637
    2 | 0.6659   | 0.7100 | 1.4764    | 1.2550
    3 | 0.7358   | 0.7430 | 1.1718    | 1.0957
    4 | 0.7780   | 0.7910 | 0.9789    | 0.9925
    5 | 0.8183   | 0.7830 | 0.8230    | 0.9633
    6 | 0.8396   | 0.7990 | 0.6989    | 0.9109
    7 | 0.8631   | 0.8170 | 0.5990    | 0.8657
    8 | 0.8796   | 0.8210 | 0.5157    | 0.8539
    9 | 0.8954   | 0.8240 | 0.4495    | 0.8503
   10 | 0.9069   | 0.8250 | 0.4038    | 0.8392
   11 | 0.9188   | 0.8320 | 0.3505    | 0.8474
   12 | 0.9271   | 0.8200 | 0.3119    | 0.8429
   13 | 0.9283   | 0.8240 | 0.2852    | 0.8628
   14 | 0.9394   | 0.8270 | 0.2460    | 0.8747
   15 | 0.9424   | 0.8230 | 0.2344    | 0.9006
   16 | 0.9445   | 0.8220 | 0.2130    | 0.9272
   17 | 0.9466   | 0.8220 | 0.2063    | 0.9376
   18 | 0.9493   | 0.8250 | 0.1889    | 0.9141
   19 | 0.9521   | 0.8220 | 0.1776    | 0.9199
   20 | 0.9555   | 0.8280 | 0.1709    | 0.9421
   21 | 0.9570   | 0.8160 | 0.1576    | 0.9840
   22 | 0.9524   | 0.8200 | 0.1594    | 0.9404
   23 | 0.9557   | 0.8230 | 0.1536    | 0.9531
   24 | 0.9546   | 0.8190 | 0.1487    | 0.9830
   25 | 0.9573   | 0.8200 | 0.1401    | 0.9731
   26 | 0.9551   | 0.8190 | 0.1411    | 0.9856
   27 | 0.9599   | 0.8250 | 0.1340    | 1.0085
   28 | 0.9579   | 0.8210 | 0.1320    | 0.9917
   29 | 0.9588   | 0.8140 | 0.1281    | 1.0339
   30 | 0.9597   | 0.8160 | 0.1232    | 1.0128

Results for Dropout Rate = 0.5:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4308   | 0.6130 | 2.6488    | 1.6574
    2 | 0.6179   | 0.6910 | 1.6562    | 1.3666
    3 | 0.6840   | 0.7160 | 1.3832    | 1.2559
    4 | 0.7120   | 0.7350 | 1.2356    | 1.1629
    5 | 0.7414   | 0.7580 | 1.1095    | 1.0926
    6 | 0.7655   | 0.7700 | 1.0050    | 1.0404
    7 | 0.7888   | 0.7830 | 0.9064    | 0.9970
    8 | 0.8018   | 0.7920 | 0.8289    | 0.9614
    9 | 0.8145   | 0.7970 | 0.7610    | 0.9465
   10 | 0.8365   | 0.8010 | 0.6888    | 0.9350
   11 | 0.8415   | 0.8150 | 0.6388    | 0.9090
   12 | 0.8559   | 0.8050 | 0.5817    | 0.9132
   13 | 0.8653   | 0.8190 | 0.5483    | 0.8996
   14 | 0.8766   | 0.8230 | 0.5012    | 0.9133
   15 | 0.8867   | 0.8180 | 0.4686    | 0.9058
   16 | 0.8882   | 0.8170 | 0.4326    | 0.9233
   17 | 0.8954   | 0.8160 | 0.4121    | 0.9289
   18 | 0.9020   | 0.8230 | 0.3792    | 0.9254
   19 | 0.9043   | 0.8230 | 0.3624    | 0.8997
   20 | 0.9075   | 0.8190 | 0.3492    | 0.9362
   21 | 0.9162   | 0.8180 | 0.3288    | 0.9450
   22 | 0.9216   | 0.8190 | 0.3084    | 0.9781
   23 | 0.9228   | 0.8200 | 0.2925    | 0.9541
   24 | 0.9228   | 0.8260 | 0.2887    | 0.9681
   25 | 0.9306   | 0.8240 | 0.2620    | 0.9984
   26 | 0.9281   | 0.8260 | 0.2678    | 0.9818
   27 | 0.9337   | 0.8290 | 0.2420    | 0.9929
   28 | 0.9311   | 0.8280 | 0.2545    | 0.9947
   29 | 0.9371   | 0.8290 | 0.2345    | 1.0121
   30 | 0.9385   | 0.8310 | 0.2272    | 1.0286

Results for Dropout Rate = 0.7:
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.3104   | 0.5380 | 3.0282    | 1.9460
    2 | 0.4995   | 0.6150 | 2.0794    | 1.6228
    3 | 0.5664   | 0.6660 | 1.8029    | 1.5083
    4 | 0.6161   | 0.6930 | 1.6339    | 1.3964
    5 | 0.6407   | 0.6980 | 1.5258    | 1.3293
    6 | 0.6607   | 0.7070 | 1.4497    | 1.2718
    7 | 0.6728   | 0.7180 | 1.3711    | 1.2266
    8 | 0.6889   | 0.7240 | 1.2941    | 1.1969
    9 | 0.7012   | 0.7300 | 1.2348    | 1.1707
   10 | 0.7067   | 0.7350 | 1.1865    | 1.1584
   11 | 0.7216   | 0.7440 | 1.1396    | 1.1375
   12 | 0.7314   | 0.7500 | 1.1113    | 1.1170
   13 | 0.7415   | 0.7570 | 1.0673    | 1.1078
   14 | 0.7498   | 0.7600 | 1.0168    | 1.0911
   15 | 0.7522   | 0.7660 | 0.9794    | 1.0836
   16 | 0.7628   | 0.7670 | 0.9492    | 1.0806
   17 | 0.7674   | 0.7740 | 0.9252    | 1.0675
   18 | 0.7766   | 0.7750 | 0.8949    | 1.0750
   19 | 0.7774   | 0.7800 | 0.8702    | 1.0513
   20 | 0.7838   | 0.7850 | 0.8570    | 1.0648
   21 | 0.7889   | 0.7820 | 0.8280    | 1.0752
   22 | 0.7923   | 0.7850 | 0.8076    | 1.0731
   23 | 0.7977   | 0.7820 | 0.7885    | 1.0868
   24 | 0.8043   | 0.7810 | 0.7610    | 1.0758
   25 | 0.8048   | 0.7860 | 0.7343    | 1.0901
   26 | 0.8063   | 0.7870 | 0.7376    | 1.0804
   27 | 0.8101   | 0.7910 | 0.7187    | 1.0902
   28 | 0.8140   | 0.7910 | 0.7003    | 1.0899
   29 | 0.8167   | 0.7920 | 0.6763    | 1.0794
   30 | 0.8212   | 0.7890 | 0.6625    | 1.1098

Best Models for 128 Neurons:
Dropout | Epoch | Train Acc | Val Acc | Train Loss | Val Loss
------------------------------------------------------------
0.3     |    11 | 0.9188   | 0.8320 | 0.3505    | 0.8474
0.5     |    30 | 0.9385   | 0.8310 | 0.2272    | 1.0286
0.7     |    29 | 0.8167   | 0.7920 | 0.6763    | 1.0794

In [27]:
import matplotlib.pyplot as plt
from tensorflow.keras import models, layers, regularizers
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import reuters
import numpy as np

# بارگذاری داده‌ها
(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=10000)

# تبدیل به one-hot
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.0
    return results

x_train = vectorize_sequences(x_train)
x_test = vectorize_sequences(x_test)

one_hot_train_labels = to_categorical(y_train)
one_hot_test_labels = to_categorical(y_test)

# تقسیم داده‌های آموزش به train و validation
x_val = x_train[:1000]
partial_x_train = x_train[1000:]

y_val = one_hot_train_labels[:1000]
partial_y_train = one_hot_train_labels[1000:]

# تابع برای آموزش و رسم نمودار با منظم‌سازی‌های مختلف
def train_and_plot(regularization_configs, neurons, epochs):
    history_dict = {}
    best_models = []  # ذخیره بهترین مدل‌ها
    
    # ساخت مدل
    def build_model(reg_type, reg_param):
        model = models.Sequential()
        if reg_type == 'dropout':
            model.add(layers.Dense(neurons, activation='relu', input_shape=(10000,)))
            model.add(layers.Dropout(reg_param))
            model.add(layers.Dense(neurons, activation='relu'))
            model.add(layers.Dropout(reg_param))
        elif reg_type == 'l1':
            model.add(layers.Dense(neurons, activation='relu', input_shape=(10000,),
                                  kernel_regularizer=regularizers.l1(reg_param)))
            model.add(layers.Dense(neurons, activation='relu',
                                  kernel_regularizer=regularizers.l1(reg_param)))
        elif reg_type == 'l2':
            model.add(layers.Dense(neurons, activation='relu', input_shape=(10000,),
                                  kernel_regularizer=regularizers.l2(reg_param)))
            model.add(layers.Dense(neurons, activation='relu',
                                  kernel_regularizer=regularizers.l2(reg_param)))
        model.add(layers.Dense(46, activation='softmax'))
        model.compile(optimizer='rmsprop',
                      loss='categorical_crossentropy',
                      metrics=['accuracy'])
        return model
    
    # آموزش مدل‌ها
    for reg_type, reg_param in regularization_configs:
        print(f"\nTraining with {reg_type} (param={reg_param}), neurons={neurons}")
        model = build_model(reg_type, reg_param)
        history = model.fit(
            partial_x_train, partial_y_train,
            epochs=epochs,
            batch_size=512,
            validation_data=(x_val, y_val),
            verbose=0
        )
        history_dict[(reg_type, reg_param)] = history
        
        # یافتن بهترین val_accuracy
        history_data = history.history
        max_val_acc = max(history_data['val_accuracy'])
        max_val_acc_epoch = history_data['val_accuracy'].index(max_val_acc) + 1
        best_model_info = {
            'reg_type': reg_type,
            'reg_param': reg_param,
            'neurons': neurons,
            'epoch': max_val_acc_epoch,
            'val_accuracy': max_val_acc,
            'val_loss': history_data['val_loss'][max_val_acc_epoch - 1],
            'train_accuracy': history_data['accuracy'][max_val_acc_epoch - 1],
            'train_loss': history_data['loss'][max_val_acc_epoch - 1]
        }
        best_models.append(best_model_info)
    
    # رسم نمودارهای جداگانه برای هر نوع منظم‌سازی
    for reg_type, reg_param in regularization_configs:
        history = history_dict[(reg_type, reg_param)].history
        
        print(f"\nResults for {reg_type} (param={reg_param}):")
        print("Epoch | Train Acc | Val Acc | Train Loss | Val Loss")
        print("-" * 50)
        for epoch in range(len(history['accuracy'])):
            print(f"{epoch+1:5d} | {history['accuracy'][epoch]:.4f}   | {history['val_accuracy'][epoch]:.4f} | {history['loss'][epoch]:.4f}    | {history['val_loss'][epoch]:.4f}")
        
        plt.figure(figsize=(12, 4))
        
        plt.subplot(1, 2, 1)
        plt.plot(history['accuracy'], label='Train Accuracy', color='blue')
        plt.plot(history['val_accuracy'], '--', label='Validation Accuracy', color='red')
        plt.title(f'Accuracy ({reg_type}={reg_param})')
        plt.xlabel('Epoch')
        plt.ylabel('Accuracy')
        plt.legend()
        plt.grid(True)
        
        plt.subplot(1, 2, 2)
        plt.plot(history['loss'], label='Train Loss', color='blue')
        plt.plot(history['val_loss'], '--', label='Validation Loss', color='red')
        plt.title(f'Loss ({reg_type}={reg_param})')
        plt.xlabel('Epoch')
        plt.ylabel('Loss')
        plt.legend()
        plt.grid(True)
        
        plt.tight_layout()
        plt.savefig(f'{reg_type}_{reg_param}_neurons_{neurons}.png')
        plt.show()
    
    # رسم نمودار مقایسه‌ای
    plt.figure(figsize=(12, 8))
    
    plt.subplot(2, 1, 1)
    for reg_type, reg_param in regularization_configs:
        plt.plot(history_dict[(reg_type, reg_param)].history['val_accuracy'],
                 label=f'{reg_type}={reg_param}')
    plt.title(f'Validation Accuracy Comparison (Neurons={neurons})')
    plt.xlabel('Epoch')
    plt.ylabel('Validation Accuracy')
    plt.legend(loc='best')
    plt.grid(True)
    
    plt.subplot(2, 1, 2)
    for reg_type, reg_param in regularization_configs:
        plt.plot(history_dict[(reg_type, reg_param)].history['val_loss'],
                 label=f'{reg_type}={reg_param}')
    plt.title(f'Validation Loss Comparison (Neurons={neurons})')
    plt.xlabel('Epoch')
    plt.ylabel('Validation Loss')
    plt.legend(loc='best')
    plt.grid(True)
    
    plt.tight_layout()
    plt.savefig(f'comparison_neurons_{neurons}.png')
    plt.show()
    
    # چاپ بهترین مدل‌ها
    print(f"\nBest Models for {neurons} Neurons:")
    print("Reg Type | Param | Epoch | Train Acc | Val Acc | Train Loss | Val Loss")
    print("-" * 70)
    for model_info in best_models:
        print(f"{model_info['reg_type']:<9} | {model_info['reg_param']:.3f} | {model_info['epoch']:5d} | "
              f"{model_info['train_accuracy']:.4f}   | {model_info['val_accuracy']:.4f} | "
              f"{model_info['train_loss']:.4f}    | {model_info['val_loss']:.4f}")

# تنظیمات منظم‌سازی
regularization_configs = [
    ('dropout', 0.3),
    ('dropout', 0.5),
    ('dropout', 0.7),
    ('l1', 0.001),
    ('l2', 0.001)
]

# اجرای آموزش برای مدل با 64 نورون (20 epoch)
print("Training Model with 64 Neurons")
train_and_plot(regularization_configs, neurons=64, epochs=20)

# اجرای آموزش برای مدل با 128 نورون (30 epoch)
print("\nTraining Model with 128 Neurons")
train_and_plot(regularization_configs, neurons=128, epochs=30)

Training Model with 64 Neurons

Training with dropout (param=0.3), neurons=64

Training with dropout (param=0.5), neurons=64

Training with dropout (param=0.7), neurons=64

Training with l1 (param=0.001), neurons=64

Training with l2 (param=0.001), neurons=64

Results for dropout (param=0.3):
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.3924   | 0.5820 | 2.8260    | 1.8991
    2 | 0.5884   | 0.6600 | 1.7884    | 1.4634
    3 | 0.6685   | 0.6990 | 1.4469    | 1.2880
    4 | 0.6983   | 0.7230 | 1.2767    | 1.1761
    5 | 0.7291   | 0.7400 | 1.1488    | 1.1000
    6 | 0.7543   | 0.7570 | 1.0367    | 1.0435
    7 | 0.7745   | 0.7760 | 0.9368    | 0.9999
    8 | 0.7969   | 0.7880 | 0.8584    | 0.9570
    9 | 0.8155   | 0.7900 | 0.7795    | 0.9289
   10 | 0.8259   | 0.8010 | 0.7149    | 0.9117
   11 | 0.8429   | 0.8060 | 0.6623    | 0.8983
   12 | 0.8510   | 0.8090 | 0.6105    | 0.8815
   13 | 0.8671   | 0.8080 | 0.5591    | 0.8792
   14 | 0.8740   | 0.8150 | 0.5159    | 0.8660
   15 | 0.8827   | 0.8100 | 0.4819    | 0.8786
   16 | 0.8901   | 0.8110 | 0.4437    | 0.8847
   17 | 0.8963   | 0.8180 | 0.4230    | 0.8801
   18 | 0.9008   | 0.8110 | 0.3854    | 0.8901
   19 | 0.9099   | 0.8130 | 0.3705    | 0.8754
   20 | 0.9089   | 0.8140 | 0.3526    | 0.8983

Results for dropout (param=0.5):
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.3269   | 0.5500 | 3.1180    | 2.1272
    2 | 0.5289   | 0.6360 | 2.1143    | 1.6318
    3 | 0.5986   | 0.6730 | 1.7441    | 1.4627
    4 | 0.6433   | 0.6910 | 1.5529    | 1.3418
    5 | 0.6681   | 0.7070 | 1.4381    | 1.2792
    6 | 0.6906   | 0.7170 | 1.3345    | 1.2126
    7 | 0.7018   | 0.7290 | 1.2464    | 1.1744
    8 | 0.7147   | 0.7360 | 1.1859    | 1.1425
    9 | 0.7304   | 0.7400 | 1.1101    | 1.1139
   10 | 0.7440   | 0.7520 | 1.0641    | 1.0812
   11 | 0.7549   | 0.7600 | 1.0075    | 1.0643
   12 | 0.7647   | 0.7630 | 0.9603    | 1.0505
   13 | 0.7696   | 0.7770 | 0.9263    | 1.0369
   14 | 0.7814   | 0.7760 | 0.8847    | 1.0300
   15 | 0.7935   | 0.7780 | 0.8366    | 1.0290
   16 | 0.7905   | 0.7770 | 0.8217    | 1.0182
   17 | 0.7989   | 0.7800 | 0.7982    | 1.0198
   18 | 0.8057   | 0.7870 | 0.7583    | 1.0217
   19 | 0.8128   | 0.7870 | 0.7310    | 1.0114
   20 | 0.8175   | 0.7890 | 0.7116    | 1.0149

Results for dropout (param=0.7):
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.2503   | 0.5350 | 3.2275    | 2.3738
    2 | 0.4171   | 0.5480 | 2.4816    | 1.8716
    3 | 0.4716   | 0.5710 | 2.1337    | 1.6834
    4 | 0.5081   | 0.6050 | 1.9658    | 1.5834
    5 | 0.5387   | 0.6370 | 1.8378    | 1.5274
    6 | 0.5664   | 0.6630 | 1.7430    | 1.4803
    7 | 0.5838   | 0.6720 | 1.6771    | 1.4299
    8 | 0.5884   | 0.6860 | 1.6152    | 1.3914
    9 | 0.6065   | 0.6960 | 1.5660    | 1.3555
   10 | 0.6218   | 0.6950 | 1.5165    | 1.3261
   11 | 0.6304   | 0.7070 | 1.4708    | 1.3093
   12 | 0.6378   | 0.7070 | 1.4403    | 1.2881
   13 | 0.6437   | 0.7150 | 1.4063    | 1.2720
   14 | 0.6540   | 0.7160 | 1.3796    | 1.2555
   15 | 0.6571   | 0.7130 | 1.3374    | 1.2483
   16 | 0.6645   | 0.7190 | 1.3112    | 1.2386
   17 | 0.6750   | 0.7230 | 1.2832    | 1.2270
   18 | 0.6817   | 0.7200 | 1.2584    | 1.2258
   19 | 0.6869   | 0.7250 | 1.2399    | 1.2219
   20 | 0.6867   | 0.7280 | 1.2221    | 1.2076

Results for l1 (param=0.001):
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4346   | 0.5500 | 6.4986    | 3.2489
    2 | 0.5798   | 0.6060 | 2.8725    | 2.6446
    3 | 0.6424   | 0.6650 | 2.5541    | 2.4511
    4 | 0.6719   | 0.6670 | 2.4057    | 2.3720
    5 | 0.6823   | 0.6890 | 2.3061    | 2.2719
    6 | 0.6929   | 0.6960 | 2.2249    | 2.1872
    7 | 0.6968   | 0.6780 | 2.1658    | 2.2025
    8 | 0.7040   | 0.6980 | 2.1198    | 2.1011
    9 | 0.7092   | 0.7090 | 2.0676    | 2.0738
   10 | 0.7164   | 0.7120 | 2.0282    | 2.0147
   11 | 0.7190   | 0.7150 | 1.9990    | 2.0017
   12 | 0.7244   | 0.7150 | 1.9626    | 1.9775
   13 | 0.7290   | 0.7230 | 1.9438    | 1.9471
   14 | 0.7339   | 0.7240 | 1.9155    | 1.9319
   15 | 0.7372   | 0.7340 | 1.8952    | 1.8982
   16 | 0.7409   | 0.7310 | 1.8717    | 1.9044
   17 | 0.7451   | 0.7300 | 1.8553    | 1.9144
   18 | 0.7483   | 0.7580 | 1.8393    | 1.8656
   19 | 0.7568   | 0.7470 | 1.8187    | 1.8768
   20 | 0.7595   | 0.7530 | 1.8047    | 1.8511

Results for l2 (param=0.001):
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4905   | 0.5940 | 2.9590    | 2.0671
    2 | 0.6538   | 0.6700 | 1.8032    | 1.6175
    3 | 0.7266   | 0.7210 | 1.4413    | 1.4127
    4 | 0.7682   | 0.7400 | 1.2246    | 1.3241
    5 | 0.8048   | 0.7720 | 1.0716    | 1.2271
    6 | 0.8317   | 0.8030 | 0.9505    | 1.1567
    7 | 0.8550   | 0.8010 | 0.8585    | 1.1391
    8 | 0.8763   | 0.8140 | 0.7860    | 1.1102
    9 | 0.8950   | 0.8120 | 0.7145    | 1.0981
   10 | 0.9043   | 0.8190 | 0.6700    | 1.0684
   11 | 0.9157   | 0.8220 | 0.6220    | 1.0769
   12 | 0.9219   | 0.8110 | 0.5946    | 1.0829
   13 | 0.9303   | 0.8340 | 0.5554    | 1.0586
   14 | 0.9344   | 0.8240 | 0.5341    | 1.0738
   15 | 0.9377   | 0.8220 | 0.5180    | 1.0702
   16 | 0.9431   | 0.8070 | 0.4966    | 1.1007
   17 | 0.9458   | 0.8170 | 0.4777    | 1.0644
   18 | 0.9488   | 0.8190 | 0.4692    | 1.0772
   19 | 0.9495   | 0.8190 | 0.4491    | 1.0770
   20 | 0.9480   | 0.8200 | 0.4525    | 1.0733

Best Models for 64 Neurons:
Reg Type | Param | Epoch | Train Acc | Val Acc | Train Loss | Val Loss
----------------------------------------------------------------------
dropout   | 0.300 |    17 | 0.8963   | 0.8180 | 0.4230    | 0.8801
dropout   | 0.500 |    20 | 0.8175   | 0.7890 | 0.7116    | 1.0149
dropout   | 0.700 |    20 | 0.6867   | 0.7280 | 1.2221    | 1.2076
l1        | 0.001 |    18 | 0.7483   | 0.7580 | 1.8393    | 1.8656
l2        | 0.001 |    13 | 0.9303   | 0.8340 | 0.5554    | 1.0586

Training Model with 128 Neurons

Training with dropout (param=0.3), neurons=128

Training with dropout (param=0.5), neurons=128

Training with dropout (param=0.7), neurons=128

Training with l1 (param=0.001), neurons=128

Training with l2 (param=0.001), neurons=128

Results for dropout (param=0.3):
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4878   | 0.6260 | 2.4694    | 1.5696
    2 | 0.6662   | 0.7050 | 1.4813    | 1.2696
    3 | 0.7299   | 0.7410 | 1.1766    | 1.1397
    4 | 0.7721   | 0.7630 | 0.9946    | 1.0369
    5 | 0.8069   | 0.7950 | 0.8462    | 0.9638
    6 | 0.8309   | 0.7900 | 0.7237    | 0.9303
    7 | 0.8569   | 0.8120 | 0.6091    | 0.8917
    8 | 0.8763   | 0.8110 | 0.5328    | 0.8798
    9 | 0.8944   | 0.8220 | 0.4584    | 0.8487
   10 | 0.9080   | 0.8190 | 0.3985    | 0.8526
   11 | 0.9208   | 0.8240 | 0.3406    | 0.8530
   12 | 0.9286   | 0.8210 | 0.3110    | 0.8671
   13 | 0.9339   | 0.8110 | 0.2679    | 0.9099
   14 | 0.9370   | 0.8190 | 0.2593    | 0.8896
   15 | 0.9409   | 0.8100 | 0.2337    | 0.9131
   16 | 0.9455   | 0.8190 | 0.2152    | 0.9068
   17 | 0.9470   | 0.8200 | 0.1982    | 0.9194
   18 | 0.9518   | 0.8170 | 0.1956    | 0.9074
   19 | 0.9528   | 0.8140 | 0.1789    | 0.9139
   20 | 0.9519   | 0.8160 | 0.1709    | 0.9262
   21 | 0.9567   | 0.8200 | 0.1603    | 0.9306
   22 | 0.9577   | 0.8140 | 0.1573    | 0.9864
   23 | 0.9592   | 0.8120 | 0.1410    | 1.0134
   24 | 0.9567   | 0.8140 | 0.1527    | 0.9622
   25 | 0.9588   | 0.8130 | 0.1364    | 0.9805
   26 | 0.9577   | 0.8210 | 0.1388    | 0.9749
   27 | 0.9570   | 0.8180 | 0.1377    | 0.9489
   28 | 0.9600   | 0.8160 | 0.1235    | 0.9967
   29 | 0.9607   | 0.8180 | 0.1270    | 1.0063
   30 | 0.9588   | 0.8150 | 0.1247    | 0.9709

Results for dropout (param=0.5):
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4316   | 0.6000 | 2.6380    | 1.6678
    2 | 0.6074   | 0.6860 | 1.6793    | 1.3688
    3 | 0.6700   | 0.7080 | 1.4189    | 1.2373
    4 | 0.7066   | 0.7310 | 1.2483    | 1.1394
    5 | 0.7347   | 0.7510 | 1.1280    | 1.0769
    6 | 0.7636   | 0.7680 | 1.0141    | 1.0298
    7 | 0.7747   | 0.7830 | 0.9429    | 0.9994
    8 | 0.7997   | 0.7940 | 0.8348    | 0.9693
    9 | 0.8126   | 0.8040 | 0.7716    | 0.9439
   10 | 0.8299   | 0.8050 | 0.6981    | 0.9414
   11 | 0.8343   | 0.8060 | 0.6621    | 0.9131
   12 | 0.8514   | 0.8160 | 0.5885    | 0.9127
   13 | 0.8627   | 0.8210 | 0.5504    | 0.9106
   14 | 0.8712   | 0.8230 | 0.5145    | 0.8998
   15 | 0.8839   | 0.8220 | 0.4726    | 0.9140
   16 | 0.8886   | 0.8260 | 0.4491    | 0.8906
   17 | 0.8959   | 0.8240 | 0.4132    | 0.9003
   18 | 0.8998   | 0.8210 | 0.3916    | 0.9394
   19 | 0.9069   | 0.8250 | 0.3670    | 0.9383
   20 | 0.9058   | 0.8210 | 0.3604    | 0.9275
   21 | 0.9182   | 0.8250 | 0.3282    | 0.9281
   22 | 0.9161   | 0.8210 | 0.3207    | 0.9348
   23 | 0.9177   | 0.8230 | 0.3092    | 0.9527
   24 | 0.9271   | 0.8210 | 0.2866    | 0.9781
   25 | 0.9253   | 0.8280 | 0.2729    | 0.9741
   26 | 0.9286   | 0.8250 | 0.2742    | 0.9793
   27 | 0.9320   | 0.8300 | 0.2550    | 0.9720
   28 | 0.9354   | 0.8300 | 0.2545    | 0.9907
   29 | 0.9342   | 0.8250 | 0.2441    | 1.0083
   30 | 0.9397   | 0.8300 | 0.2258    | 1.0390

Results for dropout (param=0.7):
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.2777   | 0.5410 | 3.1516    | 2.0466
    2 | 0.5015   | 0.6010 | 2.1085    | 1.6448
    3 | 0.5633   | 0.6550 | 1.8202    | 1.4935
    4 | 0.5991   | 0.6890 | 1.6520    | 1.3988
    5 | 0.6337   | 0.7000 | 1.5355    | 1.3276
    6 | 0.6611   | 0.7060 | 1.4416    | 1.2637
    7 | 0.6822   | 0.7130 | 1.3348    | 1.2272
    8 | 0.6913   | 0.7210 | 1.2923    | 1.1975
    9 | 0.7060   | 0.7310 | 1.2375    | 1.1694
   10 | 0.7139   | 0.7300 | 1.1783    | 1.1560
   11 | 0.7239   | 0.7420 | 1.1351    | 1.1353
   12 | 0.7315   | 0.7510 | 1.0931    | 1.1216
   13 | 0.7425   | 0.7560 | 1.0550    | 1.1223
   14 | 0.7496   | 0.7610 | 1.0157    | 1.1121
   15 | 0.7596   | 0.7680 | 0.9746    | 1.1003
   16 | 0.7704   | 0.7710 | 0.9522    | 1.0886
   17 | 0.7700   | 0.7710 | 0.9202    | 1.0875
   18 | 0.7770   | 0.7750 | 0.8814    | 1.0969
   19 | 0.7789   | 0.7810 | 0.8705    | 1.0821
   20 | 0.7900   | 0.7800 | 0.8404    | 1.0818
   21 | 0.7905   | 0.7800 | 0.8184    | 1.0848
   22 | 0.7955   | 0.7870 | 0.8025    | 1.0778
   23 | 0.7995   | 0.7880 | 0.7844    | 1.0849
   24 | 0.8041   | 0.7940 | 0.7646    | 1.0829
   25 | 0.8094   | 0.7970 | 0.7425    | 1.0817
   26 | 0.8094   | 0.8010 | 0.7349    | 1.0875
   27 | 0.8162   | 0.7970 | 0.7076    | 1.1051
   28 | 0.8173   | 0.7990 | 0.7069    | 1.1085
   29 | 0.8207   | 0.7970 | 0.6756    | 1.1182
   30 | 0.8256   | 0.8050 | 0.6590    | 1.1139

Results for l1 (param=0.001):
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4607   | 0.5720 | 9.8645    | 4.0646
    2 | 0.6144   | 0.6710 | 3.6700    | 3.4184
    3 | 0.6596   | 0.6750 | 3.3316    | 3.1914
    4 | 0.6817   | 0.6840 | 3.1075    | 3.0222
    5 | 0.6849   | 0.6930 | 2.9509    | 2.8701
    6 | 0.6906   | 0.6940 | 2.8187    | 2.7399
    7 | 0.6981   | 0.6870 | 2.6974    | 2.6660
    8 | 0.7023   | 0.6830 | 2.6156    | 2.6143
    9 | 0.7047   | 0.7050 | 2.5430    | 2.5058
   10 | 0.7119   | 0.7090 | 2.4740    | 2.4894
   11 | 0.7221   | 0.7260 | 2.4231    | 2.4353
   12 | 0.7261   | 0.7130 | 2.3925    | 2.3846
   13 | 0.7315   | 0.7320 | 2.3424    | 2.3750
   14 | 0.7380   | 0.7290 | 2.3108    | 2.3405
   15 | 0.7438   | 0.7270 | 2.2746    | 2.2895
   16 | 0.7449   | 0.7400 | 2.2547    | 2.2964
   17 | 0.7521   | 0.7150 | 2.2112    | 2.2940
   18 | 0.7547   | 0.7480 | 2.1992    | 2.2254
   19 | 0.7586   | 0.7420 | 2.1605    | 2.2169
   20 | 0.7585   | 0.7540 | 2.1526    | 2.1906
   21 | 0.7684   | 0.7610 | 2.1143    | 2.2113
   22 | 0.7641   | 0.7640 | 2.1076    | 2.1379
   23 | 0.7722   | 0.7430 | 2.0757    | 2.1433
   24 | 0.7665   | 0.7680 | 2.0700    | 2.1168
   25 | 0.7752   | 0.7550 | 2.0419    | 2.0885
   26 | 0.7761   | 0.7740 | 2.0263    | 2.0826
   27 | 0.7786   | 0.7650 | 2.0122    | 2.0747
   28 | 0.7779   | 0.7580 | 2.0039    | 2.0618
   29 | 0.7818   | 0.7790 | 1.9848    | 2.0471
   30 | 0.7855   | 0.7700 | 1.9643    | 2.0603

Results for l2 (param=0.001):
Epoch | Train Acc | Val Acc | Train Loss | Val Loss
--------------------------------------------------
    1 | 0.4900   | 0.6580 | 2.7464    | 1.9119
    2 | 0.7096   | 0.7170 | 1.6737    | 1.5897
    3 | 0.7716   | 0.7370 | 1.3588    | 1.4245
    4 | 0.8150   | 0.7870 | 1.1461    | 1.2855
    5 | 0.8494   | 0.7790 | 0.9899    | 1.2639
    6 | 0.8768   | 0.8030 | 0.8728    | 1.1838
    7 | 0.8939   | 0.8030 | 0.7938    | 1.1757
    8 | 0.9143   | 0.7880 | 0.7020    | 1.1995
    9 | 0.9221   | 0.8160 | 0.6645    | 1.1482
   10 | 0.9287   | 0.8180 | 0.6235    | 1.1172
   11 | 0.9311   | 0.8180 | 0.5987    | 1.1179
   12 | 0.9441   | 0.8000 | 0.5468    | 1.1574
   13 | 0.9456   | 0.7950 | 0.5356    | 1.2314
   14 | 0.9434   | 0.8190 | 0.5198    | 1.1163
   15 | 0.9505   | 0.7920 | 0.4975    | 1.2243
   16 | 0.9484   | 0.7920 | 0.4824    | 1.1666
   17 | 0.9471   | 0.8110 | 0.4905    | 1.1300
   18 | 0.9524   | 0.8130 | 0.4596    | 1.1153
   19 | 0.9518   | 0.7930 | 0.4553    | 1.1755
   20 | 0.9516   | 0.8050 | 0.4605    | 1.1033
   21 | 0.9540   | 0.7950 | 0.4348    | 1.1455
   22 | 0.9514   | 0.8080 | 0.4466    | 1.1354
   23 | 0.9554   | 0.8070 | 0.4184    | 1.1279
   24 | 0.9546   | 0.8170 | 0.4152    | 1.0842
   25 | 0.9550   | 0.7990 | 0.4164    | 1.1406
   26 | 0.9550   | 0.8000 | 0.4120    | 1.1501
   27 | 0.9539   | 0.8120 | 0.4028    | 1.1148
   28 | 0.9560   | 0.7680 | 0.3974    | 1.2406
   29 | 0.9529   | 0.8120 | 0.4012    | 1.0670
   30 | 0.9557   | 0.7920 | 0.3936    | 1.1553

Best Models for 128 Neurons:
Reg Type | Param | Epoch | Train Acc | Val Acc | Train Loss | Val Loss
----------------------------------------------------------------------
dropout   | 0.300 |    11 | 0.9208   | 0.8240 | 0.3406    | 0.8530
dropout   | 0.500 |    27 | 0.9320   | 0.8300 | 0.2550    | 0.9720
dropout   | 0.700 |    30 | 0.8256   | 0.8050 | 0.6590    | 1.1139
l1        | 0.001 |    29 | 0.7818   | 0.7790 | 1.9848    | 2.0471
l2        | 0.001 |    14 | 0.9434   | 0.8190 | 0.5198    | 1.1163

In [11]:
import numpy as np
from keras import models, layers, regularizers
from keras.datasets import reuters
from keras.utils import to_categorical
import matplotlib.pyplot as plt

# بارگذاری دیتاست
(train_data, train_labels), (test_data, test_labels) = reuters.load_data(num_words=10000)

# تبدیل داده‌ها به بردار
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.0
    return results

x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)
y_train = to_categorical(train_labels)
y_test = to_categorical(test_labels)

# داده‌های اعتبارسنجی
x_val = x_train[:1000]
partial_x_train = x_train[1000:]
y_val = y_train[:1000]
partial_y_train = y_train[1000:]

# پارامترهای آزمایشی
dropout_rates = [0.3, 0.5, 0.7]
l1_values = [0.0001, 0.001, 0.01]
l2_values = [0.0002,0.0001, 0.001, 0.01]

results = {}

# تابع آموزش و ارزیابی مدل
def train_model(name, model):
    print(f"Training: {name}")
    history = model.fit(partial_x_train, partial_y_train,
                        epochs=30, batch_size=512,
                        validation_data=(x_val, y_val),
                        verbose=0)
    val_acc = history.history['val_accuracy'][-1]
    results[name] = val_acc
    return val_acc

# 🟦 فقط L2 Regularization
for val in l2_values:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l2(val)))
    model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l2(val)))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"L2={val}", model)

# 🟩 فقط L1 Regularization
for val in l1_values:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l1(val)))
    model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l1(val)))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"L1={val}", model)

# 🟨 ترکیب L1 و L2
for l1_val in l1_values:
    for l2_val in l2_values:
        reg = regularizers.l1_l2(l1=l1_val, l2=l2_val)
        model = models.Sequential()
        model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=reg))
        model.add(layers.Dense(128, activation='relu', kernel_regularizer=reg))
        model.add(layers.Dense(46, activation='softmax'))
        model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
        train_model(f"L1={l1_val}_L2={l2_val}", model)

# 🟧 فقط Dropout
for rate in dropout_rates:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,)))
    model.add(layers.Dropout(rate))
    model.add(layers.Dense(128, activation='relu'))
    model.add(layers.Dropout(rate))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"Dropout={rate}", model)

# 🟥 Dropout + L2 Regularization
for rate in dropout_rates:
    for l2_val in l2_values:
        model = models.Sequential()
        model.add(layers.Dense(256, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l2(l2_val)))
        model.add(layers.Dropout(rate))
        model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l2(l2_val)))
        model.add(layers.Dropout(rate))
        model.add(layers.Dense(64, activation='relu', kernel_regularizer=regularizers.l2(l2_val)))
        model.add(layers.Dropout(rate))
        model.add(layers.Dense(46, activation='softmax'))
        model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
        train_model(f"Dropout={rate}_L2={l2_val}", model)

# نمایش بهترین مدل
best_model_name = max(results, key=results.get)
best_val_acc = results[best_model_name]

print("\nBest Model:")
print(f"{best_model_name} => Validation Accuracy: {best_val_acc:.4f}")

# چاپ همه‌ی نتایج
print("\nAll Results:")
for name, acc in sorted(results.items(), key=lambda x: x[1], reverse=True):
    print(f"{name}: {acc:.4f}")

Training: L2=0.0002
Training: L2=0.0001
Training: L2=0.001
Training: L2=0.01
Training: L1=0.0001
Training: L1=0.001
Training: L1=0.01
Training: L1=0.0001_L2=0.0002
Training: L1=0.0001_L2=0.0001
Training: L1=0.0001_L2=0.001
Training: L1=0.0001_L2=0.01
Training: L1=0.001_L2=0.0002
Training: L1=0.001_L2=0.0001
Training: L1=0.001_L2=0.001
Training: L1=0.001_L2=0.01
Training: L1=0.01_L2=0.0002
Training: L1=0.01_L2=0.0001
Training: L1=0.01_L2=0.001
Training: L1=0.01_L2=0.01
Training: Dropout=0.3
Training: Dropout=0.5
Training: Dropout=0.7
Training: Dropout=0.3_L2=0.0002
Training: Dropout=0.3_L2=0.0001
Training: Dropout=0.3_L2=0.001
Training: Dropout=0.3_L2=0.01
Training: Dropout=0.5_L2=0.0002
Training: Dropout=0.5_L2=0.0001
Training: Dropout=0.5_L2=0.001
Training: Dropout=0.5_L2=0.01
Training: Dropout=0.7_L2=0.0002
Training: Dropout=0.7_L2=0.0001
Training: Dropout=0.7_L2=0.001
Training: Dropout=0.7_L2=0.01

Best Model:
Dropout=0.5 => Validation Accuracy: 0.8270

All Results:
Dropout=0.5: 0.8270
L1=0.0001_L2=0.001: 0.8230
Dropout=0.3_L2=0.0002: 0.8210
L1=0.0001_L2=0.0001: 0.8200
Dropout=0.3: 0.8180
Dropout=0.3_L2=0.0001: 0.8180
Dropout=0.3_L2=0.001: 0.8140
L2=0.001: 0.8090
Dropout=0.5_L2=0.0001: 0.8060
L2=0.01: 0.8040
L1=0.0001_L2=0.0002: 0.8040
L2=0.0001: 0.8020
L1=0.0001: 0.8020
Dropout=0.7: 0.8000
L2=0.0002: 0.7990
Dropout=0.5_L2=0.0002: 0.7990
Dropout=0.5_L2=0.001: 0.7910
L1=0.0001_L2=0.01: 0.7700
L1=0.001_L2=0.0002: 0.7690
L1=0.001: 0.7680
L1=0.001_L2=0.0001: 0.7670
L1=0.001_L2=0.001: 0.7530
Dropout=0.3_L2=0.01: 0.7370
Dropout=0.5_L2=0.01: 0.7190
Dropout=0.7_L2=0.0002: 0.7190
Dropout=0.7_L2=0.001: 0.7160
L1=0.001_L2=0.01: 0.7150
Dropout=0.7_L2=0.0001: 0.7120
Dropout=0.7_L2=0.01: 0.6800
L1=0.01: 0.5830
L1=0.01_L2=0.0001: 0.5820
L1=0.01_L2=0.001: 0.5800
L1=0.01_L2=0.0002: 0.5790
L1=0.01_L2=0.01: 0.5760

In [2]:
import numpy as np
from keras import models, layers, regularizers
from keras.datasets import reuters
from keras.utils import to_categorical
import matplotlib.pyplot as plt

# بارگذاری دیتاست
(train_data, train_labels), (test_data, test_labels) = reuters.load_data(num_words=10000)

# تبدیل داده‌ها به بردار
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.0
    return results

x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)
y_train = to_categorical(train_labels)
y_test = to_categorical(test_labels)

# داده‌های اعتبارسنجی
x_val = x_train[:1000]
partial_x_train = x_train[1000:]
y_val = y_train[:1000]
partial_y_train = y_train[1000:]

# پارامترهای آزمایشی
dropout_rates = [0.3, 0.5, 0.7]
l1_values = [0.0001, 0.001, 0.01]
l2_values = [0.0001, 0.001, 0.01]

results = {}

# تابع آموزش و ارزیابی مدل
def train_model(name, model):
    print(f"Training: {name}")
    history = model.fit(partial_x_train, partial_y_train,
                        epochs=30, batch_size=512,
                        validation_data=(x_val, y_val),
                        verbose=0)
    
    # ذخیره نتیجه
    val_acc = history.history['val_accuracy'][-1]
    results[name] = val_acc

    # 🎯 رسم نمودار برای هر مدل
    acc = history.history['accuracy']
    val_acc_list = history.history['val_accuracy']
    loss = history.history['loss']
    val_loss = history.history['val_loss']
    epochs = range(1, len(acc) + 1)

    plt.figure(figsize=(10, 4))
    plt.suptitle(f"{name}", fontsize=14)

    # نمودار دقت
    plt.subplot(1, 2, 1)
    plt.plot(epochs, acc, color='navy', marker='o', label='Training Accuracy')
    plt.plot(epochs, val_acc_list, color='pink', marker='o', label='Validation Accuracy')
    plt.title('Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()

    # نمودار خطا
    plt.subplot(1, 2, 2)
    plt.plot(epochs, loss, color='navy', marker='o', label='Training Loss')
    plt.plot(epochs, val_loss, color='pink', marker='o', label='Validation Loss')
    plt.title('Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

    return val_acc


# 🟦 فقط L2 Regularization
for val in l2_values:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l2(val)))
    model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l2(val)))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"L2={val}", model)

# 🟩 فقط L1 Regularization
for val in l1_values:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l1(val)))
    model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l1(val)))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"L1={val}", model)

# 🟨 ترکیب L1 و L2
for l1_val in l1_values:
    for l2_val in l2_values:
        reg = regularizers.l1_l2(l1=l1_val, l2=l2_val)
        model = models.Sequential()
        model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=reg))
        model.add(layers.Dense(128, activation='relu', kernel_regularizer=reg))
        model.add(layers.Dense(46, activation='softmax'))
        model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
        train_model(f"L1={l1_val}_L2={l2_val}", model)

# 🟧 فقط Dropout
for rate in dropout_rates:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,)))
    model.add(layers.Dropout(rate))
    model.add(layers.Dense(128, activation='relu'))
    model.add(layers.Dropout(rate))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"Dropout={rate}", model)

# 🟥 Dropout + L2 Regularization
for rate in dropout_rates:
    for l2_val in l2_values:
        model = models.Sequential()
        model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l2(l2_val)))
        model.add(layers.Dropout(rate))
        model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l2(l2_val)))
        model.add(layers.Dropout(rate))
        model.add(layers.Dense(46, activation='softmax'))
        model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
        train_model(f"Dropout={rate}_L2={l2_val}", model)

# نمایش بهترین مدل
best_model_name = max(results, key=results.get)
best_val_acc = results[best_model_name]

print("\nBest Model:")
print(f"{best_model_name} => Validation Accuracy: {best_val_acc:.4f}")

# چاپ همه‌ی نتایج
print("\nAll Results:")
for name, acc in sorted(results.items(), key=lambda x: x[1], reverse=True):
    print(f"{name}: {acc:.4f}")

Training: L2=0.0001

Training: L2=0.001

Training: L2=0.01

Training: L1=0.0001

Training: L1=0.001

Training: L1=0.01

Training: L1=0.0001_L2=0.0001

Training: L1=0.0001_L2=0.001

Training: L1=0.0001_L2=0.01

Training: L1=0.001_L2=0.0001

Training: L1=0.001_L2=0.001

Training: L1=0.001_L2=0.01

Training: L1=0.01_L2=0.0001

Training: L1=0.01_L2=0.001

Training: L1=0.01_L2=0.01

Training: Dropout=0.3

Training: Dropout=0.5

Training: Dropout=0.7

Training: Dropout=0.3_L2=0.0001

Training: Dropout=0.3_L2=0.001

Training: Dropout=0.3_L2=0.01

Training: Dropout=0.5_L2=0.0001

Training: Dropout=0.5_L2=0.001

Training: Dropout=0.5_L2=0.01

Training: Dropout=0.7_L2=0.0001

Training: Dropout=0.7_L2=0.001

Training: Dropout=0.7_L2=0.01

Best Model:
Dropout=0.5 => Validation Accuracy: 0.8250

All Results:
Dropout=0.5: 0.8250
Dropout=0.3_L2=0.001: 0.8230
Dropout=0.5_L2=0.0001: 0.8220
Dropout=0.5_L2=0.001: 0.8180
Dropout=0.3: 0.8130
Dropout=0.3_L2=0.0001: 0.8110
L2=0.0001: 0.8060
L2=0.001: 0.8040
L1=0.0001: 0.8030
L1=0.0001_L2=0.0001: 0.8010
L1=0.0001_L2=0.001: 0.7980
Dropout=0.7: 0.7980
Dropout=0.7_L2=0.0001: 0.7950
Dropout=0.7_L2=0.001: 0.7850
L2=0.01: 0.7770
Dropout=0.5_L2=0.01: 0.7760
L1=0.0001_L2=0.01: 0.7620
L1=0.001_L2=0.001: 0.7610
L1=0.001: 0.7570
L1=0.001_L2=0.0001: 0.7530
Dropout=0.3_L2=0.01: 0.7520
Dropout=0.7_L2=0.01: 0.7300
L1=0.001_L2=0.01: 0.7150
L1=0.01_L2=0.001: 0.5840
L1=0.01_L2=0.0001: 0.5800
L1=0.01: 0.5770
L1=0.01_L2=0.01: 0.5770

In [ ]:
import numpy as np
from keras import models, layers, regularizers
from keras.datasets import reuters
from keras.utils import to_categorical
import matplotlib.pyplot as plt
import pandas as pd

# بارگذاری دیتاست
(train_data, train_labels), (test_data, test_labels) = reuters.load_data(num_words=10000)

# تبدیل داده‌ها به بردار
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.0
    return results

x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)
y_train = to_categorical(train_labels)
y_test = to_categorical(test_labels)

# داده‌های اعتبارسنجی
x_val = x_train[:1000]
partial_x_train = x_train[1000:]
y_val = y_train[:1000]
partial_y_train = y_train[1000:]

# پارامترهای آزمایشی
dropout_rates = [0.3, 0.5, 0.7]
l1_values = [0.0001, 0.001, 0.01]
l2_values = [0.0001, 0.001, 0.01]

results = {}

# دیکشنری برای ذخیره مقادیر
metrics = {
    'Model': [],
    'Train Loss': [],
    'Val Loss': [],
    'Train Accuracy': [],
    'Val Accuracy': []
}

# تابع آموزش و ارزیابی مدل با ذخیره مقادیر
def train_model(name, model):
    print(f"Training: {name}")
    history = model.fit(partial_x_train, partial_y_train,
                        epochs=30, batch_size=512,
                        validation_data=(x_val, y_val),
                        verbose=0)
    
    # ذخیره نتایج دقت و خطا
    val_acc = history.history['val_accuracy'][-1]
    results[name] = val_acc
    
    metrics['Model'].append(name)
    metrics['Train Loss'].append(history.history['loss'][-1])
    metrics['Val Loss'].append(history.history['val_loss'][-1])
    metrics['Train Accuracy'].append(history.history['accuracy'][-1])
    metrics['Val Accuracy'].append(history.history['val_accuracy'][-1])

    return val_acc

# 🟦 فقط L2 Regularization
for val in l2_values:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l2(val)))
    model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l2(val)))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"L2={val}", model)

# 🟩 فقط L1 Regularization
for val in l1_values:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l1(val)))
    model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l1(val)))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"L1={val}", model)

# 🟨 ترکیب L1 و L2
for l1_val in l1_values:
    for l2_val in l2_values:
        reg = regularizers.l1_l2(l1=l1_val, l2=l2_val)
        model = models.Sequential()
        model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=reg))
        model.add(layers.Dense(128, activation='relu', kernel_regularizer=reg))
        model.add(layers.Dense(46, activation='softmax'))
        model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
        train_model(f"L1={l1_val}_L2={l2_val}", model)

# 🟧 فقط Dropout
for rate in dropout_rates:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,)))
    model.add(layers.Dropout(rate))
    model.add(layers.Dense(128, activation='relu'))
    model.add(layers.Dropout(rate))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"Dropout={rate}", model)

# 🟥 Dropout + L2 Regularization
for rate in dropout_rates:
    for l2_val in l2_values:
        model = models.Sequential()
        model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l2(l2_val)))
        model.add(layers.Dropout(rate))
        model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l2(l2_val)))
        model.add(layers.Dropout(rate))
        model.add(layers.Dense(46, activation='softmax'))
        model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
        train_model(f"Dropout={rate}_L2={l2_val}", model)

# ذخیره کردن نتایج در یک DataFrame برای نمایش
df = pd.DataFrame(metrics)

# نمایش نتایج در یک جدول (با مرتب کردن بر اساس دقت اعتبارسنجی)
# df.sort_values(by='Val Accuracy', ascending=False, inplace=True)

# نمایش جدول
df

Training: L2=0.0001
Training: L2=0.001
Training: L2=0.01
Training: L1=0.0001
Training: L1=0.001
Training: L1=0.01
Training: L1=0.0001_L2=0.0001
Training: L1=0.0001_L2=0.001
Training: L1=0.0001_L2=0.01
Training: L1=0.001_L2=0.0001
Training: L1=0.001_L2=0.001
Training: L1=0.001_L2=0.01
Training: L1=0.01_L2=0.0001
Training: L1=0.01_L2=0.001
Training: L1=0.01_L2=0.01
Training: Dropout=0.3
Training: Dropout=0.5
Training: Dropout=0.7
Training: Dropout=0.3_L2=0.0001
Training: Dropout=0.3_L2=0.001
Training: Dropout=0.3_L2=0.01
Training: Dropout=0.5_L2=0.0001
Training: Dropout=0.5_L2=0.001
Training: Dropout=0.5_L2=0.01
Training: Dropout=0.7_L2=0.0001
Training: Dropout=0.7_L2=0.001
Training: Dropout=0.7_L2=0.01

                    Model  Train Loss  Val Loss  Train Accuracy  Val Accuracy
18  Dropout=0.3_L2=0.0001    0.201459  1.029228        0.959659         0.828
16            Dropout=0.5    0.226047  1.045498        0.940867         0.828
21  Dropout=0.5_L2=0.0001    0.305849  1.072247        0.936733         0.822
22   Dropout=0.5_L2=0.001    0.595067  1.122800        0.917063         0.818
6     L1=0.0001_L2=0.0001    0.641006  1.327997        0.945001         0.814
7      L1=0.0001_L2=0.001    0.831243  1.346330        0.928589         0.812
15            Dropout=0.3    0.125279  1.019586        0.961413         0.811
0               L2=0.0001    0.173471  1.018178        0.956778         0.808
19   Dropout=0.3_L2=0.001    0.457132  1.114084        0.949511         0.804
3               L1=0.0001    0.630686  1.287431        0.946129         0.802
1                L2=0.001    0.382264  1.101183        0.957655         0.802
24  Dropout=0.7_L2=0.0001    0.721930  1.150187        0.827362         0.800
17            Dropout=0.7    0.674468  1.106817        0.825482         0.800
2                 L2=0.01    1.122104  1.349832        0.836507         0.794
25   Dropout=0.7_L2=0.001    0.948187  1.217430        0.813455         0.784
20    Dropout=0.3_L2=0.01    1.172349  1.344827        0.815084         0.776
23    Dropout=0.5_L2=0.01    1.284527  1.369989        0.782010         0.771
8       L1=0.0001_L2=0.01    1.325366  1.475937        0.798046         0.770
10      L1=0.001_L2=0.001    1.997281  2.077627        0.769607         0.765
4                L1=0.001    1.983138  2.044292        0.774868         0.764
9      L1=0.001_L2=0.0001    1.992790  2.098869        0.775370         0.740
26    Dropout=0.7_L2=0.01    1.442321  1.424084        0.721498         0.722
11       L1=0.001_L2=0.01    2.140906  2.168785        0.718116         0.703
13       L1=0.01_L2=0.001    8.412078  8.308174        0.573916         0.578
5                 L1=0.01    7.954227  7.855939        0.577424         0.577
14        L1=0.01_L2=0.01    8.438596  8.379178        0.571160         0.577
12      L1=0.01_L2=0.0001    8.365965  8.271941        0.576798         0.575

In [5]:
import numpy as np
from keras import models, layers, regularizers
from keras.datasets import reuters
from keras.utils import to_categorical
import matplotlib.pyplot as plt
import pandas as pd

# بارگذاری دیتاست
(train_data, train_labels), (test_data, test_labels) = reuters.load_data(num_words=10000)

# تبدیل داده‌ها به بردار
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.0
    return results

x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)
y_train = to_categorical(train_labels)
y_test = to_categorical(test_labels)

# داده‌های اعتبارسنجی
x_val = x_train[:1000]
partial_x_train = x_train[1000:]
y_val = y_train[:1000]
partial_y_train = y_train[1000:]

# پارامترهای آزمایشی
dropout_rates = [0.3, 0.5, 0.7]
l1_values = [0.0001, 0.001, 0.01]
l2_values = [0.0001, 0.001, 0.01]

results = {}

# دیکشنری برای ذخیره مقادیر
metrics = {
    'Model': [],
    'Train Loss': [],
    'Val Loss': [],
    'Train Accuracy': [],
    'Val Accuracy': []
}

# تابع آموزش و ارزیابی مدل با ذخیره مقادیر
def train_model(name, model):
    print(f"Training: {name}")
    history = model.fit(partial_x_train, partial_y_train,
                        epochs=30, batch_size=512,
                        validation_data=(x_val, y_val),
                        verbose=0)
    
    # ذخیره نتایج دقت و خطا
    val_acc = history.history['val_accuracy'][-1]
    results[name] = val_acc
    
    metrics['Model'].append(name)
    metrics['Train Loss'].append(history.history['loss'][-1])
    metrics['Val Loss'].append(history.history['val_loss'][-1])
    metrics['Train Accuracy'].append(history.history['accuracy'][-1])
    metrics['Val Accuracy'].append(history.history['val_accuracy'][-1])

    return val_acc

# 🟦 فقط L2 Regularization
for val in l2_values:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l2(val)))
    model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l2(val)))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"L2={val}", model)

# 🟩 فقط L1 Regularization
for val in l1_values:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l1(val)))
    model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l1(val)))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"L1={val}", model)

# 🟨 ترکیب L1 و L2
for l1_val in l1_values:
    for l2_val in l2_values:
        reg = regularizers.l1_l2(l1=l1_val, l2=l2_val)
        model = models.Sequential()
        model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=reg))
        model.add(layers.Dense(128, activation='relu', kernel_regularizer=reg))
        model.add(layers.Dense(46, activation='softmax'))
        model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
        train_model(f"L1={l1_val}_L2={l2_val}", model)

# 🟧 فقط Dropout
for rate in dropout_rates:
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu', input_shape=(10000,)))
    model.add(layers.Dropout(rate))
    model.add(layers.Dense(128, activation='relu'))
    model.add(layers.Dropout(rate))
    model.add(layers.Dense(46, activation='softmax'))
    model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
    train_model(f"Dropout={rate}", model)

# 🟥 Dropout + L2 Regularization
for rate in dropout_rates:
    for l2_val in l2_values:
        model = models.Sequential()
        model.add(layers.Dense(128, activation='relu', input_shape=(10000,), kernel_regularizer=regularizers.l2(l2_val)))
        model.add(layers.Dropout(rate))
        model.add(layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l2(l2_val)))
        model.add(layers.Dropout(rate))
        model.add(layers.Dense(46, activation='softmax'))
        model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
        train_model(f"Dropout={rate}_L2={l2_val}", model)

# ذخیره کردن نتایج در یک DataFrame برای نمایش
df = pd.DataFrame(metrics)

# نمایش نتایج در یک جدول (با مرتب کردن بر اساس دقت اعتبارسنجی)
# df.sort_values(by='Val Accuracy', ascending=False, inplace=True)

# نمایش جدول
df

Training: L2=0.0001
Training: L2=0.001
Training: L2=0.01
Training: L1=0.0001
Training: L1=0.001
Training: L1=0.01
Training: L1=0.0001_L2=0.0001
Training: L1=0.0001_L2=0.001
Training: L1=0.0001_L2=0.01
Training: L1=0.001_L2=0.0001
Training: L1=0.001_L2=0.001
Training: L1=0.001_L2=0.01
Training: L1=0.01_L2=0.0001
Training: L1=0.01_L2=0.001
Training: L1=0.01_L2=0.01
Training: Dropout=0.3
Training: Dropout=0.5
Training: Dropout=0.7
Training: Dropout=0.3_L2=0.0001
Training: Dropout=0.3_L2=0.001
Training: Dropout=0.3_L2=0.01
Training: Dropout=0.5_L2=0.0001
Training: Dropout=0.5_L2=0.001
Training: Dropout=0.5_L2=0.01
Training: Dropout=0.7_L2=0.0001
Training: Dropout=0.7_L2=0.001
Training: Dropout=0.7_L2=0.01

                    Model  Train Loss  Val Loss  Train Accuracy  Val Accuracy
0               L2=0.0001    0.171340  1.039125        0.958406         0.801
1                L2=0.001    0.396448  1.132429        0.954899         0.801
2                 L2=0.01    1.128368  1.373345        0.831496         0.776
3               L1=0.0001    0.623848  1.259043        0.946003         0.812
4                L1=0.001    1.978270  2.049554        0.778752         0.768
5                 L1=0.01    7.992329  7.902697        0.579429         0.578
6     L1=0.0001_L2=0.0001    0.653312  1.299090        0.938236         0.815
7      L1=0.0001_L2=0.001    0.813633  1.368408        0.931721         0.809
8       L1=0.0001_L2=0.01    1.316150  1.453035        0.808945         0.776
9      L1=0.001_L2=0.0001    1.980057  2.046266        0.777625         0.764
10      L1=0.001_L2=0.001    1.994652  2.072563        0.773741         0.757
11       L1=0.001_L2=0.01    2.117926  2.154094        0.717489         0.713
12      L1=0.01_L2=0.0001    8.399673  8.302643        0.575420         0.576
13       L1=0.01_L2=0.001    8.408421  8.296887        0.573039         0.579
14        L1=0.01_L2=0.01    8.408473  8.343438        0.578802         0.589
15            Dropout=0.3    0.117800  1.021266        0.962415         0.817
16            Dropout=0.5    0.218290  1.047768        0.939614         0.821
17            Dropout=0.7    0.665254  1.129824        0.826610         0.806
18  Dropout=0.3_L2=0.0001    0.202901  1.016062        0.957905         0.819
19   Dropout=0.3_L2=0.001    0.459728  1.090940        0.947883         0.810
20    Dropout=0.3_L2=0.01    1.183367  1.359850        0.809070         0.771
21  Dropout=0.5_L2=0.0001    0.294943  1.077804        0.940491         0.827
22   Dropout=0.5_L2=0.001    0.601591  1.118440        0.915685         0.820
23    Dropout=0.5_L2=0.01    1.275678  1.404974        0.781508         0.750
24  Dropout=0.7_L2=0.0001    0.723715  1.163113        0.828865         0.807
25   Dropout=0.7_L2=0.001    0.942154  1.202090        0.813581         0.796
26    Dropout=0.7_L2=0.01    1.466842  1.423056        0.714984         0.708